#!/usr/bin/env python3
"""Build a compact pilot report without pooling dependent samples or picking a seed."""
import argparse
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def read(path, mode, sanitized):
    data = json.loads((path / 'results.json').read_text())
    if data['status'] != 'passed' or data['mode'] != mode or data['sanitize'] != sanitized:
        raise ValueError(f'wrong or incomplete campaign: {path}')
    if len(data['runs']) != data['planned_runs']:
        raise ValueError('incomplete run count')
    for source, expected in data['source_sha256'].items():
        if hashlib.sha256((path / 'snapshot' / source).read_bytes()).hexdigest() != expected:
            raise ValueError(f'snapshot changed: {source}')
    for build in data['builds']:
        binary = Path(build['binary'])
        header = binary.parent / 'runtime/minyar_bounded_rc.h'
        if hashlib.sha256(binary.read_bytes()).hexdigest() != build['binary_sha256']:
            raise ValueError(f'binary changed: {binary}')
        if hashlib.sha256(header.read_bytes()).hexdigest() != build['scheduler_sha256']:
            raise ValueError(f'variant changed: {header}')
    for row in data['runs']:
        if row['trace_sha256']:
            trace = path / (row['label'] + '.csv')
            if hashlib.sha256(trace.read_bytes()).hexdigest() != row['trace_sha256']:
                raise ValueError(f'trace changed: {trace}')
    return data


def signature(row):
    s = row['summary']
    return row['policy'], row['budget'], s['shape'], s['nodes'], s['seed']


def compare_transcripts(path, manifest):
    index = {signature(r): r for r in manifest['runs']}
    count = 0
    for key, row in index.items():
        if key[0] != 'current':
            continue
        other = index.get(('fair-unit', *key[1:]))
        if other is None:
            raise ValueError('missing matched fair-unit case')
        if (path / (row['label'] + '.csv')).read_bytes() != (path / (other['label'] + '.csv')).read_bytes():
            raise ValueError(f'optimized/reference accounting transcript differs: {key}')
        count += 1
    return count


def span(values, divisor=1):
    if not values or all(v is None for v in values):
        return '—'
    if any(v is None for v in values):
        raise ValueError('partially missing measurement')
    return f'{min(values)/divisor:.3f}–{max(values)/divisor:.3f}'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    for name in ['diagnostic', 'sanitize', 'sampled', 'batch', 'output']:
        p.add_argument('--' + name, type=Path, required=True)
    args = p.parse_args()
    def link(target):
        return Path(os.path.relpath(target.resolve(), args.output.resolve().parent)).as_posix()
    manifests = {name: read(getattr(args, name), mode, sanitize) for name, mode, sanitize in
                 [('diagnostic', 'diagnostic', False), ('sanitize', 'diagnostic', True),
                  ('sampled', 'sampled', False), ('batch', 'batch', False)]}
    # Notebook prose and the reporter may change; actual executable input cannot.
    reference = manifests['diagnostic']['source_sha256']
    code_inputs = [x for x in reference if x.startswith('runtime/') or x.endswith('/probe.c')
                   or x.endswith('/variants.py')]
    for data in manifests.values():
        if any(data['source_sha256'].get(x) != reference[x] for x in code_inputs):
            raise ValueError('campaigns use different runtime, fixture, or transformation sources')
    if manifests['sampled']['compiler_version'] != manifests['batch']['compiler_version']:
        raise ValueError('timing compilers differ')
    if manifests['sampled']['host'] != manifests['batch']['host']:
        raise ValueError('timing hosts differ')
    native_pairs = compare_transcripts(args.diagnostic, manifests['diagnostic'])
    sanitize_pairs = compare_transcripts(args.sanitize, manifests['sanitize'])
    sampled = {signature(r): r for r in manifests['sampled']['runs']}
    batch = {signature(r): r for r in manifests['batch']['runs']}
    if sampled.keys() != batch.keys():
        raise ValueError('timing modes do not have matching workloads')
    lines = ['# Initial scheduler pilot results', '',
             'Generated by `report.py` from retained manifests and hash-checked traces.', '',
             f"Host: {manifests['sampled']['host']}. Serial fresh-process runs; system allocation; Clang `-O2`.", '',
             f"- Native diagnostic cases: {len(manifests['diagnostic']['runs'])}, all passed.",
             f"- ASan/UBSan diagnostic cases: {len(manifests['sanitize']['runs'])}, all passed.",
             f'- Exact current/fair-unit accounting transcript pairs: {native_pairs} native, {sanitize_pairs} sanitized.',
             f'- Timing cases: {len(sampled)} sampled, {len(batch)} batch; all completed and validated.', '',
             'These graph/frame cases do not cover Text-view destruction. The historical K1',
             'counterexample and subsequent fix require separate evidence. Passing this matrix does not',
             f'establish the universal public-operation bound; see [formal obligations]({link(Path(__file__).parent / "formal-model.md")}).', '',
             '## K32 comparison', '',
             'Every cell is the minimum–maximum across all process/seed repetitions in its row.',
             'The p99 cell is a range of per-process poll p99s, never a pooled percentile.',
             'Batch drain uses separate runs without per-poll clocks. Values include host noise.', '',
             'Minimum positive empty-clock-pair differences across sampled processes: '
             + span([r['summary']['clock_positive_min_ns'] for r in sampled.values()]) + ' ns.',
             'Zero samples, if present, mean below the observed timer granularity, not zero cost.',
             f'The [protocol amendment]({link(Path(__file__).parent / "protocol.md")}#clock-amendment-before-the-second-campaign)',
             'records the coarse-clock initial campaign and the reason for rerunning it.', '',
             '| Shape | Nodes | Policy | Processes per mode | Initial retirement, µs | Poll p99, µs | Batch complete drain, ms |',
             '| --- | ---: | --- | ---: | ---: | ---: | ---: |']
    groups = {}
    for key, row in sampled.items():
        policy, budget, shape, nodes, seed = key
        if budget == 32 or policy == 'eager':
            groups.setdefault((shape, nodes, policy), []).append(key)
    for (shape, nodes, policy), keys in sorted(groups.items()):
        lines.append(f'| {shape} | {nodes} | {policy} | {len(keys)} | '
                     + span([sampled[k]['summary']['initial_ns'] for k in keys], 1000) + ' | '
                     + span([sampled[k]['metrics']['poll_p99_ns'] for k in keys], 1000) + ' | '
                     + span([batch[k]['summary']['elapsed_ns'] for k in keys], 1000000) + ' |')
    lines += ['', '## Evidence and interpretation', '',
              'All K1/K32/K128 raw measurements and diagnostic post-retirement managed-byte',
              'metrics remain in the manifests below. Diagnostic sizes differ from timing sizes;',
              'do not combine their byte figures into a timing/space ratio.', '',
              'This is a synthetic mechanism pilot. It does not establish performance on real',
              'applications, sustained backlog recovery, a scheduler advantage across workloads,',
              'or novelty relative to CTRC. Eager is a whole-profile comparison and changes owner',
              'representation as well as reclamation scheduling.', '']
    for name in manifests:
        directory = getattr(args, name).resolve()
        target = link(directory / 'results.json')
        lines.append(f'- [{name} manifest]({target})')
    lines += ['', '`build/` evidence is local and removed by `make clean`. Preserve snapshots and',
              'raw traces before citing these values in a paper.', '']
    args.output.write_text('\n'.join(lines))
    print(args.output)


if __name__ == '__main__':
    main()
