; Generated by the compiler written in Minyar.

@.text.data.154 = private unnamed_addr constant [5 x i8] c"tail\00"
@.text.154 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.154, i64 4, i64 4, ptr null, ptr null }
@.text.data.169 = private unnamed_addr constant [8 x i8] c"tail127\00"
@.text.169 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.169, i64 7, i64 7, ptr null, ptr null }
@.text.data.768 = private unnamed_addr constant [6 x i8] c"quote\00"
@.text.768 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.768, i64 5, i64 5, ptr null, ptr null }
@.text.data.770 = private unnamed_addr constant [5 x i8] c"tail\00"
@.text.770 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.770, i64 4, i64 4, ptr null, ptr null }
@.text.data.844 = private unnamed_addr constant [4 x i8] c"new\00"
@.text.844 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.844, i64 3, i64 3, ptr null, ptr null }
@.text.data.846 = private unnamed_addr constant [7 x i8] c"member\00"
@.text.846 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.846, i64 6, i64 6, ptr null, ptr null }

declare void @minyar_rc_enter(i64)
declare void @minyar_rc_leave()
declare void @minyar_stack_enter()
declare void @minyar_stack_leave()
declare void @minyar_rc_keep(ptr)
declare void @minyar_rc_borrow(ptr)
declare void @minyar_rc_retain(ptr)
declare void @minyar_rc_local(i64, ptr)
declare void @minyar_rc_local_take(i64, ptr)
declare void @minyar_rc_local_move(i64)
declare void @minyar_rc_step()
declare void @minyar_print_integer(i64)
declare void @minyar_print_text(ptr)
declare void @minyar_print_character(i32)
declare void @minyar_print_boolean(i1)
declare void @minyar_fail(ptr)
declare void @minyar_exit(i64)
declare void @minyar_print_float(double)
declare void @minyar_record_replace(ptr, i64, i64, i64)
declare i64 @minyar_bytes_get(ptr, i64)
declare void @minyar_bytes_set(ptr, i64, i64)
declare i64 @minyar_bytes_length(ptr)
declare i1 @minyar_file_exists(ptr)
declare ptr @minyar_bytes_new(i64)
declare void @minyar_bytes_resize(ptr, i64)
declare void @minyar_bytes_clear(ptr)
declare void @minyar_bytes_add(ptr, i64)
declare void @minyar_bytes_append(ptr, ptr)
declare ptr @minyar_bytes_slice(ptr, i64, i64)
declare ptr @minyar_read_bytes_file(ptr)
declare void @minyar_write_bytes_file(ptr, ptr)
declare void @minyar_bytes_add_int16(ptr, i64)
declare void @minyar_bytes_set_int16(ptr, i64, i64)
declare i64 @minyar_bytes_get_int16(ptr, i64)
declare void @minyar_bytes_add_uint16(ptr, i64)
declare void @minyar_bytes_set_uint16(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint16(ptr, i64)
declare void @minyar_bytes_add_int32(ptr, i64)
declare void @minyar_bytes_set_int32(ptr, i64, i64)
declare i64 @minyar_bytes_get_int32(ptr, i64)
declare void @minyar_bytes_add_uint32(ptr, i64)
declare void @minyar_bytes_set_uint32(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint32(ptr, i64)
declare void @minyar_bytes_add_int64(ptr, i64)
declare void @minyar_bytes_set_int64(ptr, i64, i64)
declare i64 @minyar_bytes_get_int64(ptr, i64)
declare void @minyar_bytes_add_float32(ptr, double)
declare void @minyar_bytes_set_float32(ptr, i64, double)
declare double @minyar_bytes_get_float32(ptr, i64)
declare void @minyar_bytes_add_float64(ptr, double)
declare void @minyar_bytes_set_float64(ptr, i64, double)
declare double @minyar_bytes_get_float64(ptr, i64)
declare ptr @minyar_float_text(double)
declare i64 @minyar_float_integer(double)
declare i32 @minyar_integer_character(i64)
declare i64 @minyar_integer_absolute(i64)
declare void @minyar_check_clamp_integer(i64, i64)
declare void @minyar_check_clamp_float(double, double)
declare void @minyar_check_shift(i64)
declare double @minyar_tan(double)
declare double @minyar_asin(double)
declare double @minyar_acos(double)
declare double @minyar_atan(double)
declare double @minyar_atan2(double, double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)
declare i1 @minyar_texts_are_equal(ptr, ptr)
declare ptr @minyar_join_text(ptr, ptr)
declare ptr @minyar_join_text_take_left(ptr, ptr)
declare ptr @minyar_join_texts(ptr)
declare i64 @minyar_text_length(ptr)
declare i64 @minyar_text_byte_length(ptr)
declare i32 @minyar_text_character_at(ptr, i64)
declare ptr @minyar_text_slice(ptr, i64, i64)
declare ptr @minyar_integer_text(i64)
declare ptr @minyar_character_text(i32)
declare ptr @minyar_boolean_text(i1)
declare void @minyar_initialize_arguments(i32, ptr)
declare i64 @minyar_argument_count()
declare ptr @minyar_argument(i64)
declare ptr @minyar_read_text_file(ptr)
declare void @minyar_write_text_file(ptr, ptr)
declare ptr @minyar_list_new()
declare void @minyar_list_references(ptr)
declare void @minyar_list_add(ptr, i64)
declare void @minyar_list_add_take(ptr, i64)
declare i64 @minyar_list_length(ptr)
declare i64 @minyar_list_get(ptr, i64)
declare void @minyar_list_set(ptr, i64, i64)
declare void @minyar_list_set_take(ptr, i64, i64)
declare ptr @minyar_list_appended(ptr, i64, i64, i64)
declare ptr @minyar_record_new(i64)
declare ptr @minyar_record_new_scalar(i64)
declare i64 @minyar_record_get(ptr, i64)
declare void @minyar_record_set(ptr, i64, i64)
declare void @minyar_record_set_scalar(ptr, i64, i64)
declare void @minyar_record_set_reference(ptr, i64, i64)
declare void @minyar_record_set_take(ptr, i64, i64)
declare void @minyar_check_integer_overflow(i1)
declare void @minyar_check_integer_division(i64, i64)
declare void @minyar_fail_integer_overflow() cold noreturn
declare void @minyar_fail_integer_division(i64) cold noreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)


; Checked inline List accesses. ABI: { values pointer, length, capacity }.
define internal i64 @.minyar.list.get.checked(ptr %list, i64 %position) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %get.valid = icmp ult i64 %position, %length
  br i1 %get.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  %value = load i64, ptr %slot
  ret i64 %value
bad:
  %fallback = call i64 @minyar_list_get(ptr %list, i64 %position)
  ret i64 %fallback
}
define internal void @.minyar.list.set.scalar.checked(ptr %list, i64 %position, i64 %value) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %set.valid = icmp ult i64 %position, %length
  br i1 %set.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  store i64 %value, ptr %slot
  ret void
bad:
  call void @minyar_list_set(ptr %list, i64 %position, i64 %value)
  ret void
}

define internal i64 @.minyar.list.length(ptr %list) alwaysinline sanitize_address {
entry:
  %pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %pointer
  ret i64 %length
}

define internal void @.minyar.integer.overflow.checked(i1 %overflow) alwaysinline sanitize_address {
entry:
  br i1 %overflow, label %bad, label %good
bad:
  call void @minyar_fail_integer_overflow()
  unreachable
good:
  ret void
}
define internal void @.minyar.integer.division.checked(i64 %left, i64 %right) alwaysinline sanitize_address {
entry:
  %zero = icmp eq i64 %right, 0
  %minimum = icmp eq i64 %left, -9223372036854775808
  %negative.one = icmp eq i64 %right, -1
  %overflow = and i1 %minimum, %negative.one
  %invalid = or i1 %zero, %overflow
  br i1 %invalid, label %bad, label %good
bad:
  call void @minyar_fail_integer_division(i64 %right)
  unreachable
good:
  ret void
}

define internal void @.minyar.shift.checked(i64 %count) alwaysinline sanitize_address {
entry:
  %valid = icmp ult i64 %count, 64
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_shift(i64 %count)
  ret void
good:
  ret void
}
define internal i32 @.minyar.character.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %range = icmp ult i64 %value, 1114112
  %below = icmp ult i64 %value, 55296
  %above = icmp ugt i64 %value, 57343
  %scalar = or i1 %below, %above
  %valid = and i1 %range, %scalar
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i32 @minyar_integer_character(i64 %value)
  ret i32 %fallback
good:
  %result = trunc i64 %value to i32
  ret i32 %result
}
define internal i64 @.minyar.float.integer.checked(double %value) alwaysinline sanitize_address {
entry:
  %above.minimum = fcmp oge double %value, -9.223372036854775808e18
  %below.maximum = fcmp olt double %value, 9.223372036854775808e18
  %valid = and i1 %above.minimum, %below.maximum
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_float_integer(double %value)
  ret i64 %fallback
good:
  %result = fptosi double %value to i64
  ret i64 %result
}
define internal i64 @.minyar.integer.absolute.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %valid = icmp ne i64 %value, -9223372036854775808
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_integer_absolute(i64 %value)
  ret i64 %fallback
good:
  %negative = icmp slt i64 %value, 0
  %negated = sub i64 0, %value
  %result = select i1 %negative, i64 %negated, i64 %value
  ret i64 %result
}
define internal void @.minyar.clamp.integer.checked(i64 %lower, i64 %upper) alwaysinline sanitize_address {
entry:
  %valid = icmp sle i64 %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_integer(i64 %lower, i64 %upper)
  ret void
good:
  ret void
}
define internal void @.minyar.clamp.float.checked(double %lower, double %upper) alwaysinline sanitize_address {
entry:
  %valid = fcmp ole double %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_float(double %lower, double %upper)
  ret void
good:
  ret void
}
define ptr @.minyar.fn.produce(ptr %argument.0, i64 %argument.1) sanitize_address {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 1)
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %local.5 = alloca i64
  %value.0 = call i64 @.minyar.list.get.checked(ptr %argument.0, i64 0)
  %checked.1 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.0, i64 1)
  %value.1 = extractvalue { i64, i1 } %checked.1, 0
  %overflow.1 = extractvalue { i64, i1 } %checked.1, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.1)
  call void @.minyar.list.set.scalar.checked(ptr %argument.0, i64 0, i64 %value.1)
  %value.2 = call i64 @.minyar.list.get.checked(ptr %argument.0, i64 2)
  %checked.3 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.2, i64 10)
  %value.3 = extractvalue { i64, i1 } %checked.3, 0
  %overflow.3 = extractvalue { i64, i1 } %checked.3, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.3)
  %checked.4 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.3, i64 1)
  %value.4 = extractvalue { i64, i1 } %checked.4, 0
  %overflow.4 = extractvalue { i64, i1 } %checked.4, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.4)
  call void @.minyar.list.set.scalar.checked(ptr %argument.0, i64 2, i64 %value.4)
  %value.5 = call ptr @minyar_list_new()
  call void @minyar_rc_local_take(i64 0, ptr %value.5)
  store ptr %value.5, ptr %local.2
  store i64 0, ptr %local.3
  store i64 %argument.1, ptr %local.4
  br label %for.condition.0

for.condition.0:
  %value.6 = load i64, ptr %local.3
  %value.7 = load i64, ptr %local.4
  %value.8 = icmp slt i64 %value.6, %value.7
  br i1 %value.8, label %for.body.1, label %for.end.3

for.body.1:
  store i64 %value.6, ptr %local.5
  %value.9 = load ptr, ptr %local.2
  %value.10 = load i64, ptr %local.5
  %checked.11 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.10, i64 37)
  %value.11 = extractvalue { i64, i1 } %checked.11, 0
  %overflow.11 = extractvalue { i64, i1 } %checked.11, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.11)
  %checked.12 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.11, i64 11)
  %value.12 = extractvalue { i64, i1 } %checked.12, 0
  %overflow.12 = extractvalue { i64, i1 } %checked.12, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.12)
  call void @minyar_list_add(ptr %value.9, i64 %value.12)
  br label %for.step.2

for.step.2:
  %value.13 = load i64, ptr %local.3
  %value.14 = add nsw i64 %value.13, 1
  store i64 %value.14, ptr %local.3
  call void @minyar_rc_step()
  br label %for.condition.0

for.end.3:
  %value.15 = load ptr, ptr %local.2
  call void @minyar_rc_retain(ptr %value.15)
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret ptr %value.15
}

define i64 @.minyar.fn.allocatingTail(ptr %argument.0) sanitize_address {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 1)
  %local.1 = alloca i64
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %value.0 = call i64 @.minyar.list.get.checked(ptr %argument.0, i64 1)
  %checked.1 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.0, i64 1)
  %value.1 = extractvalue { i64, i1 } %checked.1, 0
  %overflow.1 = extractvalue { i64, i1 } %checked.1, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.1)
  call void @.minyar.list.set.scalar.checked(ptr %argument.0, i64 1, i64 %value.1)
  %value.2 = call i64 @.minyar.list.get.checked(ptr %argument.0, i64 2)
  %checked.3 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.2, i64 10)
  %value.3 = extractvalue { i64, i1 } %checked.3, 0
  %overflow.3 = extractvalue { i64, i1 } %checked.3, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.3)
  %checked.4 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.3, i64 2)
  %value.4 = extractvalue { i64, i1 } %checked.4, 0
  %overflow.4 = extractvalue { i64, i1 } %checked.4, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.4)
  call void @.minyar.list.set.scalar.checked(ptr %argument.0, i64 2, i64 %value.4)
  %value.5 = call ptr @minyar_list_new()
  call void @minyar_list_references(ptr %value.5)
  call void @minyar_rc_local_take(i64 0, ptr %value.5)
  store ptr %value.5, ptr %local.1
  store i64 0, ptr %local.2
  store i64 128, ptr %local.3
  br label %for.condition.0

for.condition.0:
  %value.6 = load i64, ptr %local.2
  %value.7 = load i64, ptr %local.3
  %value.8 = icmp slt i64 %value.6, %value.7
  br i1 %value.8, label %for.body.1, label %for.end.3

for.body.1:
  store i64 %value.6, ptr %local.4
  %value.9 = load ptr, ptr %local.1
  %value.10 = load i64, ptr %local.4
  %value.11 = call ptr @minyar_integer_text(i64 %value.10)
  call void @minyar_rc_keep(ptr %value.11)
  %value.12 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.154, i64 8), ptr %value.11)
  %value.13 = ptrtoint ptr %value.12 to i64
  call void @minyar_list_add_take(ptr %value.9, i64 %value.13)
  call void @minyar_rc_step()
  br label %for.step.2

for.step.2:
  %value.14 = load i64, ptr %local.2
  %value.15 = add nsw i64 %value.14, 1
  store i64 %value.15, ptr %local.2
  call void @minyar_rc_step()
  br label %for.condition.0

for.end.3:
  call void @minyar_rc_step()
  %value.16 = load ptr, ptr %local.1
  %value.17 = call i64 @.minyar.list.get.checked(ptr %value.16, i64 127)
  %value.18 = inttoptr i64 %value.17 to ptr
  call void @minyar_rc_borrow(ptr %value.18)
  %value.19 = call i1 @minyar_texts_are_equal(ptr %value.18, ptr getelementptr (i8, ptr @.text.169, i64 8))
  %value.20 = xor i1 %value.19, true
  br i1 %value.20, label %if.then.4, label %if.end.6

if.then.4:
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i64 -1

if.end.6:
  call void @minyar_rc_step()
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i64 313
}

define i32 @main(i32 %minyar.argument.count, ptr %minyar.argument.values) sanitize_address {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 19)
  %local.0 = alloca i64
  %local.1 = alloca i64
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %local.5 = alloca i64
  %local.6 = alloca i64
  %local.7 = alloca i64
  %local.8 = alloca i64
  %local.9 = alloca i64
  %local.10 = alloca i64
  %local.11 = alloca i64
  %local.12 = alloca i64
  %local.13 = alloca i64
  %local.14 = alloca i64
  %local.15 = alloca i64
  %local.16 = alloca i64
  %local.17 = alloca i64
  %local.18 = alloca i64
  %local.19 = alloca i64
  %local.20 = alloca i64
  %local.21 = alloca i64
  %local.22 = alloca i64
  %local.23 = alloca i64
  %local.24 = alloca i64
  %local.25 = alloca i64
  %local.26 = alloca i64
  %local.27 = alloca i64
  %local.28 = alloca i64
  %local.29 = alloca i64
  %local.30 = alloca i64
  call void @minyar_initialize_arguments(i32 %minyar.argument.count, ptr %minyar.argument.values)
  %value.0 = call ptr @minyar_list_new()
  call void @minyar_list_add(ptr %value.0, i64 0)
  call void @minyar_list_add(ptr %value.0, i64 0)
  call void @minyar_list_add(ptr %value.0, i64 0)
  call void @minyar_rc_local_take(i64 0, ptr %value.0)
  store ptr %value.0, ptr %local.0
  %value.1 = load ptr, ptr %local.0
  %value.2 = call ptr @.minyar.fn.produce(ptr %value.1, i64 3)
  call void @minyar_rc_local_take(i64 1, ptr %value.2)
  store ptr %value.2, ptr %local.1
  %value.3 = load ptr, ptr %local.1
  call void @minyar_rc_local(i64 2, ptr %value.3)
  store ptr %value.3, ptr %local.2
  %value.4 = load ptr, ptr %local.1
  %value.5 = load ptr, ptr %local.0
  %value.6 = call i64 @.minyar.fn.allocatingTail(ptr %value.5)
  %value.7 = call ptr @minyar_list_appended(ptr %value.4, i64 %value.6, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 3, ptr %value.7)
  store ptr %value.7, ptr %local.3
  %value.8 = load ptr, ptr %local.0
  %value.9 = call i64 @.minyar.list.get.checked(ptr %value.8, i64 2)
  call void @minyar_print_integer(i64 %value.9)
  %value.10 = load ptr, ptr %local.0
  %value.11 = call i64 @.minyar.list.get.checked(ptr %value.10, i64 0)
  call void @minyar_print_integer(i64 %value.11)
  %value.12 = load ptr, ptr %local.0
  %value.13 = call i64 @.minyar.list.get.checked(ptr %value.12, i64 1)
  call void @minyar_print_integer(i64 %value.13)
  %value.14 = load ptr, ptr %local.2
  %value.15 = call i64 @.minyar.list.length(ptr %value.14)
  call void @minyar_print_integer(i64 %value.15)
  %value.16 = load ptr, ptr %local.3
  %value.17 = call i64 @.minyar.list.length(ptr %value.16)
  call void @minyar_print_integer(i64 %value.17)
  %value.18 = load ptr, ptr %local.2
  call void @minyar_rc_local(i64 4, ptr %value.18)
  store ptr %value.18, ptr %local.6
  store i64 0, ptr %local.4
  br label %for.condition.0

for.condition.0:
  %value.19 = load i64, ptr %local.4
  %value.20 = load ptr, ptr %local.6
  %value.21 = call i64 @minyar_list_length(ptr %value.20)
  %value.22 = icmp slt i64 %value.19, %value.21
  br i1 %value.22, label %for.body.1, label %for.end.3

for.body.1:
  %value.23 = load ptr, ptr %local.6
  %value.24 = call i64 @.minyar.list.get.checked(ptr %value.23, i64 %value.19)
  store i64 %value.24, ptr %local.7
  %value.25 = load i64, ptr %local.7
  call void @minyar_print_integer(i64 %value.25)
  br label %for.step.2

for.step.2:
  %value.26 = load i64, ptr %local.4
  %value.27 = add nsw i64 %value.26, 1
  store i64 %value.27, ptr %local.4
  call void @minyar_rc_step()
  br label %for.condition.0

for.end.3:
  call void @minyar_rc_local(i64 4, ptr null)
  %value.28 = load ptr, ptr %local.3
  call void @minyar_rc_local(i64 5, ptr %value.28)
  store ptr %value.28, ptr %local.10
  store i64 0, ptr %local.8
  br label %for.condition.4

for.condition.4:
  %value.29 = load i64, ptr %local.8
  %value.30 = load ptr, ptr %local.10
  %value.31 = call i64 @minyar_list_length(ptr %value.30)
  %value.32 = icmp slt i64 %value.29, %value.31
  br i1 %value.32, label %for.body.5, label %for.end.7

for.body.5:
  %value.33 = load ptr, ptr %local.10
  %value.34 = call i64 @.minyar.list.get.checked(ptr %value.33, i64 %value.29)
  store i64 %value.34, ptr %local.11
  %value.35 = load i64, ptr %local.11
  call void @minyar_print_integer(i64 %value.35)
  br label %for.step.6

for.step.6:
  %value.36 = load i64, ptr %local.8
  %value.37 = add nsw i64 %value.36, 1
  store i64 %value.37, ptr %local.8
  call void @minyar_rc_step()
  br label %for.condition.4

for.end.7:
  call void @minyar_rc_local(i64 5, ptr null)
  %value.38 = load ptr, ptr %local.1
  call void @.minyar.list.set.scalar.checked(ptr %value.38, i64 1, i64 701)
  %value.39 = load ptr, ptr %local.3
  %value.40 = call i64 @.minyar.list.get.checked(ptr %value.39, i64 1)
  call void @minyar_print_integer(i64 %value.40)
  %value.41 = load ptr, ptr %local.3
  call void @.minyar.list.set.scalar.checked(ptr %value.41, i64 2, i64 907)
  %value.42 = load ptr, ptr %local.2
  %value.43 = call i64 @.minyar.list.get.checked(ptr %value.42, i64 2)
  call void @minyar_print_integer(i64 %value.43)
  %value.44 = load ptr, ptr %local.2
  call void @minyar_rc_local(i64 6, ptr %value.44)
  store ptr %value.44, ptr %local.14
  store i64 0, ptr %local.12
  br label %for.condition.8

for.condition.8:
  %value.45 = load i64, ptr %local.12
  %value.46 = load ptr, ptr %local.14
  %value.47 = call i64 @minyar_list_length(ptr %value.46)
  %value.48 = icmp slt i64 %value.45, %value.47
  br i1 %value.48, label %for.body.9, label %for.end.11

for.body.9:
  %value.49 = load ptr, ptr %local.14
  %value.50 = call i64 @.minyar.list.get.checked(ptr %value.49, i64 %value.45)
  store i64 %value.50, ptr %local.15
  %value.51 = load i64, ptr %local.15
  call void @minyar_print_integer(i64 %value.51)
  br label %for.step.10

for.step.10:
  %value.52 = load i64, ptr %local.12
  %value.53 = add nsw i64 %value.52, 1
  store i64 %value.53, ptr %local.12
  call void @minyar_rc_step()
  br label %for.condition.8

for.end.11:
  call void @minyar_rc_local(i64 6, ptr null)
  %value.54 = load ptr, ptr %local.3
  call void @minyar_rc_local(i64 7, ptr %value.54)
  store ptr %value.54, ptr %local.18
  store i64 0, ptr %local.16
  br label %for.condition.12

for.condition.12:
  %value.55 = load i64, ptr %local.16
  %value.56 = load ptr, ptr %local.18
  %value.57 = call i64 @minyar_list_length(ptr %value.56)
  %value.58 = icmp slt i64 %value.55, %value.57
  br i1 %value.58, label %for.body.13, label %for.end.15

for.body.13:
  %value.59 = load ptr, ptr %local.18
  %value.60 = call i64 @.minyar.list.get.checked(ptr %value.59, i64 %value.55)
  store i64 %value.60, ptr %local.19
  %value.61 = load i64, ptr %local.19
  call void @minyar_print_integer(i64 %value.61)
  br label %for.step.14

for.step.14:
  %value.62 = load i64, ptr %local.16
  %value.63 = add nsw i64 %value.62, 1
  store i64 %value.63, ptr %local.16
  call void @minyar_rc_step()
  br label %for.condition.12

for.end.15:
  call void @minyar_rc_local(i64 7, ptr null)
  %value.64 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.64, i64 0, i64 0)
  %value.65 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.65, i64 1, i64 0)
  %value.66 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.66, i64 2, i64 0)
  %value.67 = load ptr, ptr %local.0
  %value.68 = call ptr @.minyar.fn.produce(ptr %value.67, i64 3)
  call void @minyar_rc_keep(ptr %value.68)
  %value.69 = load ptr, ptr %local.0
  %value.70 = call i64 @.minyar.fn.allocatingTail(ptr %value.69)
  %value.71 = call ptr @minyar_list_appended(ptr %value.68, i64 %value.70, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 8, ptr %value.71)
  store ptr %value.71, ptr %local.20
  call void @minyar_rc_step()
  %value.72 = load ptr, ptr %local.0
  %value.73 = call i64 @.minyar.list.get.checked(ptr %value.72, i64 2)
  call void @minyar_print_integer(i64 %value.73)
  %value.74 = load ptr, ptr %local.0
  %value.75 = call i64 @.minyar.list.get.checked(ptr %value.74, i64 0)
  call void @minyar_print_integer(i64 %value.75)
  %value.76 = load ptr, ptr %local.0
  %value.77 = call i64 @.minyar.list.get.checked(ptr %value.76, i64 1)
  call void @minyar_print_integer(i64 %value.77)
  %value.78 = load ptr, ptr %local.20
  %value.79 = call i64 @.minyar.list.length(ptr %value.78)
  call void @minyar_print_integer(i64 %value.79)
  %value.80 = load ptr, ptr %local.20
  %value.81 = call i64 @.minyar.list.get.checked(ptr %value.80, i64 0)
  call void @minyar_print_integer(i64 %value.81)
  %value.82 = load ptr, ptr %local.20
  %value.83 = call i64 @.minyar.list.get.checked(ptr %value.82, i64 1)
  call void @minyar_print_integer(i64 %value.83)
  %value.84 = load ptr, ptr %local.20
  %value.85 = call i64 @.minyar.list.get.checked(ptr %value.84, i64 2)
  call void @minyar_print_integer(i64 %value.85)
  %value.86 = load ptr, ptr %local.20
  %value.87 = call i64 @.minyar.list.get.checked(ptr %value.86, i64 3)
  call void @minyar_print_integer(i64 %value.87)
  %value.88 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.88, i64 0, i64 0)
  %value.89 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.89, i64 1, i64 0)
  %value.90 = load ptr, ptr %local.0
  call void @.minyar.list.set.scalar.checked(ptr %value.90, i64 2, i64 0)
  %value.91 = load ptr, ptr %local.0
  %value.92 = call ptr @.minyar.fn.produce(ptr %value.91, i64 0)
  call void @minyar_rc_keep(ptr %value.92)
  %value.93 = load ptr, ptr %local.0
  %value.94 = call i64 @.minyar.fn.allocatingTail(ptr %value.93)
  %value.95 = call ptr @minyar_list_appended(ptr %value.92, i64 %value.94, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 9, ptr %value.95)
  store ptr %value.95, ptr %local.21
  call void @minyar_rc_step()
  %value.96 = load ptr, ptr %local.0
  %value.97 = call i64 @.minyar.list.get.checked(ptr %value.96, i64 2)
  call void @minyar_print_integer(i64 %value.97)
  %value.98 = load ptr, ptr %local.0
  %value.99 = call i64 @.minyar.list.get.checked(ptr %value.98, i64 0)
  call void @minyar_print_integer(i64 %value.99)
  %value.100 = load ptr, ptr %local.0
  %value.101 = call i64 @.minyar.list.get.checked(ptr %value.100, i64 1)
  call void @minyar_print_integer(i64 %value.101)
  %value.102 = load ptr, ptr %local.21
  %value.103 = call i64 @.minyar.list.length(ptr %value.102)
  call void @minyar_print_integer(i64 %value.103)
  %value.104 = load ptr, ptr %local.21
  %value.105 = call i64 @.minyar.list.get.checked(ptr %value.104, i64 0)
  call void @minyar_print_integer(i64 %value.105)
  %value.106 = call ptr @minyar_list_new()
  %value.107 = zext i1 true to i64
  call void @minyar_list_add(ptr %value.106, i64 %value.107)
  %value.108 = zext i1 false to i64
  call void @minyar_list_add(ptr %value.106, i64 %value.108)
  call void @minyar_rc_local_take(i64 10, ptr %value.106)
  store ptr %value.106, ptr %local.22
  %value.109 = load ptr, ptr %local.22
  %value.110 = zext i1 true to i64
  %value.111 = call ptr @minyar_list_appended(ptr %value.109, i64 %value.110, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 11, ptr %value.111)
  store ptr %value.111, ptr %local.23
  %value.112 = load ptr, ptr %local.22
  %value.113 = zext i1 false to i64
  call void @.minyar.list.set.scalar.checked(ptr %value.112, i64 0, i64 %value.113)
  %value.114 = load ptr, ptr %local.22
  %value.115 = call i64 @.minyar.list.get.checked(ptr %value.114, i64 0)
  %value.116 = trunc i64 %value.115 to i1
  call void @minyar_print_boolean(i1 %value.116)
  %value.117 = load ptr, ptr %local.22
  %value.118 = call i64 @.minyar.list.get.checked(ptr %value.117, i64 1)
  %value.119 = trunc i64 %value.118 to i1
  call void @minyar_print_boolean(i1 %value.119)
  %value.120 = load ptr, ptr %local.23
  %value.121 = call i64 @.minyar.list.get.checked(ptr %value.120, i64 0)
  %value.122 = trunc i64 %value.121 to i1
  call void @minyar_print_boolean(i1 %value.122)
  %value.123 = load ptr, ptr %local.23
  %value.124 = call i64 @.minyar.list.get.checked(ptr %value.123, i64 1)
  %value.125 = trunc i64 %value.124 to i1
  call void @minyar_print_boolean(i1 %value.125)
  %value.126 = load ptr, ptr %local.23
  %value.127 = call i64 @.minyar.list.get.checked(ptr %value.126, i64 2)
  %value.128 = trunc i64 %value.127 to i1
  call void @minyar_print_boolean(i1 %value.128)
  %value.129 = call ptr @minyar_list_new()
  %value.130 = call i32 @.minyar.character.checked(i64 233)
  %value.131 = zext i32 %value.130 to i64
  call void @minyar_list_add(ptr %value.129, i64 %value.131)
  %value.132 = call i32 @.minyar.character.checked(i64 128578)
  %value.133 = zext i32 %value.132 to i64
  call void @minyar_list_add(ptr %value.129, i64 %value.133)
  call void @minyar_rc_local_take(i64 12, ptr %value.129)
  store ptr %value.129, ptr %local.24
  %value.134 = load ptr, ptr %local.24
  %value.135 = call i32 @.minyar.character.checked(i64 65)
  %value.136 = zext i32 %value.135 to i64
  %value.137 = call ptr @minyar_list_appended(ptr %value.134, i64 %value.136, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 13, ptr %value.137)
  store ptr %value.137, ptr %local.25
  %value.138 = load ptr, ptr %local.24
  %value.139 = call i32 @.minyar.character.checked(i64 66)
  %value.140 = zext i32 %value.139 to i64
  call void @.minyar.list.set.scalar.checked(ptr %value.138, i64 0, i64 %value.140)
  %value.141 = load ptr, ptr %local.24
  %value.142 = call i64 @.minyar.list.get.checked(ptr %value.141, i64 0)
  %value.143 = trunc i64 %value.142 to i32
  %value.144 = zext i32 %value.143 to i64
  call void @minyar_print_integer(i64 %value.144)
  %value.145 = load ptr, ptr %local.24
  %value.146 = call i64 @.minyar.list.get.checked(ptr %value.145, i64 1)
  %value.147 = trunc i64 %value.146 to i32
  %value.148 = zext i32 %value.147 to i64
  call void @minyar_print_integer(i64 %value.148)
  %value.149 = load ptr, ptr %local.25
  %value.150 = call i64 @.minyar.list.get.checked(ptr %value.149, i64 0)
  %value.151 = trunc i64 %value.150 to i32
  %value.152 = zext i32 %value.151 to i64
  call void @minyar_print_integer(i64 %value.152)
  %value.153 = load ptr, ptr %local.25
  %value.154 = call i64 @.minyar.list.get.checked(ptr %value.153, i64 1)
  %value.155 = trunc i64 %value.154 to i32
  %value.156 = zext i32 %value.155 to i64
  call void @minyar_print_integer(i64 %value.156)
  %value.157 = load ptr, ptr %local.25
  %value.158 = call i64 @.minyar.list.get.checked(ptr %value.157, i64 2)
  %value.159 = trunc i64 %value.158 to i32
  %value.160 = zext i32 %value.159 to i64
  call void @minyar_print_integer(i64 %value.160)
  %value.161 = call ptr @minyar_list_new()
  %value.162 = bitcast double 5.0e-1 to i64
  call void @minyar_list_add(ptr %value.161, i64 %value.162)
  %value.163 = bitcast double 1.25e0 to i64
  call void @minyar_list_add(ptr %value.161, i64 %value.163)
  call void @minyar_rc_local_take(i64 14, ptr %value.161)
  store ptr %value.161, ptr %local.26
  %value.164 = load ptr, ptr %local.26
  %value.165 = bitcast double 2.25e0 to i64
  %value.166 = call ptr @minyar_list_appended(ptr %value.164, i64 %value.165, i64 0, i64 0)
  call void @minyar_rc_local_take(i64 15, ptr %value.166)
  store ptr %value.166, ptr %local.27
  %value.167 = load ptr, ptr %local.26
  %value.168 = bitcast double 7.5e0 to i64
  call void @.minyar.list.set.scalar.checked(ptr %value.167, i64 0, i64 %value.168)
  %value.169 = load ptr, ptr %local.26
  %value.170 = call i64 @.minyar.list.get.checked(ptr %value.169, i64 0)
  %value.171 = bitcast i64 %value.170 to double
  call void @minyar_print_float(double %value.171)
  %value.172 = load ptr, ptr %local.26
  %value.173 = call i64 @.minyar.list.get.checked(ptr %value.172, i64 1)
  %value.174 = bitcast i64 %value.173 to double
  call void @minyar_print_float(double %value.174)
  %value.175 = load ptr, ptr %local.27
  %value.176 = call i64 @.minyar.list.get.checked(ptr %value.175, i64 0)
  %value.177 = bitcast i64 %value.176 to double
  call void @minyar_print_float(double %value.177)
  %value.178 = load ptr, ptr %local.27
  %value.179 = call i64 @.minyar.list.get.checked(ptr %value.178, i64 1)
  %value.180 = bitcast i64 %value.179 to double
  call void @minyar_print_float(double %value.180)
  %value.181 = load ptr, ptr %local.27
  %value.182 = call i64 @.minyar.list.get.checked(ptr %value.181, i64 2)
  %value.183 = bitcast i64 %value.182 to double
  call void @minyar_print_float(double %value.183)
  %value.184 = call ptr @minyar_record_new(i64 2)
  call void @minyar_record_set(ptr %value.184, i64 0, i64 71)
  %value.185 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.768, i64 8), ptr getelementptr (i8, ptr @.text.770, i64 8))
  %value.186 = ptrtoint ptr %value.185 to i64
  call void @minyar_record_set_take(ptr %value.184, i64 1, i64 %value.186)
  call void @minyar_rc_local_take(i64 16, ptr %value.184)
  store ptr %value.184, ptr %local.28
  %value.187 = call ptr @minyar_list_new()
  call void @minyar_list_references(ptr %value.187)
  %value.188 = load ptr, ptr %local.28
  %value.189 = ptrtoint ptr %value.188 to i64
  call void @minyar_list_add(ptr %value.187, i64 %value.189)
  call void @minyar_rc_local_take(i64 17, ptr %value.187)
  store ptr %value.187, ptr %local.29
  %value.190 = load ptr, ptr %local.29
  %value.191 = load ptr, ptr %local.28
  %value.192 = ptrtoint ptr %value.191 to i64
  %value.193 = call ptr @minyar_list_appended(ptr %value.190, i64 %value.192, i64 1, i64 0)
  call void @minyar_rc_local_take(i64 18, ptr %value.193)
  store ptr %value.193, ptr %local.30
  %value.194 = load ptr, ptr %local.28
  call void @minyar_record_set_scalar(ptr %value.194, i64 0, i64 73)
  %value.195 = load ptr, ptr %local.29
  %value.196 = call i64 @.minyar.list.get.checked(ptr %value.195, i64 0)
  %value.197 = inttoptr i64 %value.196 to ptr
  %value.198 = call i64 @minyar_record_get(ptr %value.197, i64 0)
  call void @minyar_print_integer(i64 %value.198)
  %value.199 = load ptr, ptr %local.30
  %value.200 = call i64 @.minyar.list.get.checked(ptr %value.199, i64 0)
  %value.201 = inttoptr i64 %value.200 to ptr
  %value.202 = call i64 @minyar_record_get(ptr %value.201, i64 0)
  call void @minyar_print_integer(i64 %value.202)
  %value.203 = load ptr, ptr %local.30
  %value.204 = call i64 @.minyar.list.get.checked(ptr %value.203, i64 1)
  %value.205 = inttoptr i64 %value.204 to ptr
  %value.206 = call i64 @minyar_record_get(ptr %value.205, i64 0)
  call void @minyar_print_integer(i64 %value.206)
  %value.207 = load ptr, ptr %local.29
  %value.208 = call ptr @minyar_record_new(i64 2)
  call void @minyar_record_set(ptr %value.208, i64 0, i64 90)
  %value.209 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.844, i64 8), ptr getelementptr (i8, ptr @.text.846, i64 8))
  %value.210 = ptrtoint ptr %value.209 to i64
  call void @minyar_record_set_take(ptr %value.208, i64 1, i64 %value.210)
  %value.211 = ptrtoint ptr %value.208 to i64
  call void @minyar_list_set_take(ptr %value.207, i64 0, i64 %value.211)
  %value.212 = load ptr, ptr %local.29
  %value.213 = call i64 @.minyar.list.get.checked(ptr %value.212, i64 0)
  %value.214 = inttoptr i64 %value.213 to ptr
  %value.215 = call i64 @minyar_record_get(ptr %value.214, i64 0)
  call void @minyar_print_integer(i64 %value.215)
  %value.216 = load ptr, ptr %local.30
  %value.217 = call i64 @.minyar.list.get.checked(ptr %value.216, i64 0)
  %value.218 = inttoptr i64 %value.217 to ptr
  %value.219 = call i64 @minyar_record_get(ptr %value.218, i64 0)
  call void @minyar_print_integer(i64 %value.219)
  %value.220 = load ptr, ptr %local.30
  %value.221 = call i64 @.minyar.list.get.checked(ptr %value.220, i64 1)
  %value.222 = inttoptr i64 %value.221 to ptr
  %value.223 = call i64 @minyar_record_get(ptr %value.222, i64 0)
  call void @minyar_print_integer(i64 %value.223)
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i32 0
}

