"""Author and check research documents only. Never imports or runs peer/local tests."""
import json,re,hashlib,datetime,collections
from pathlib import Path
ROOT=Path.cwd(); E=ROOT/'evidence/peer-readonly/go-zig-round3'; R=ROOT/'research/2026-10-memory'
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
S=json.loads((E/'sources.json').read_text()); source={x['path']:x for x in S}
zig=(E/'array.zig.txt').read_text().splitlines()
def closing(lines,start):
 depth=0
 for i in range(start-1,len(lines)):
  depth+=lines[i].count('{')-lines[i].count('}')
  if depth==0:return i+1
 raise ValueError(start)
C={
'literal':('tests/recursive-data.py',[148,171],'Ordered effectful List literal values 1,2,3; literal function arguments 7/seven; Boolean/Character and nested Text empty context. Different exact values/shape from selected peer cases.'),
'capture':('tests/recursive-data.py',[173,184],'Captured earlier record projection survives later List replacement; old!,new!,new!. Replacement lifetime, not deep copying.'),
'empty':('tests/recursive-data.py',[199,210],'Contextual empty return/reassignment length0; nested typed literal reads2. No comptime empty pointer coercion.'),
'reject':('tests/recursive-data.py',[186,197],'Homogeneous literal and Nothing/separator diagnostics; does not implement tuple coercion or zero-bit storage.'),
'nested':('tests/conformance/loops-and-assignment/program.min',[53,55],'Two nested literal rows with one scalar mutation/read. Does not check cross-row independence.'),
'fresh':('tests/peer-research-semantics.py',[67,78],'Ten dynamically constructed independent rows; mutation yields -1,10,99. Does not cover capturing/copying a row.'),
'record':('tests/conformance/records/program.min',[1,10],'Explicit record and nested List construction; Ada,36,language projections. All fields supplied.'),
'fields':('tests/bootstrap-records.py',[43,56],'Existing missing/duplicate/unknown-field and wrong-type diagnostics. Source only; no bootstrap invocation here.'),
'effects':('tests/scalar-record-initialization.py',[28,36],'Effectful record field initializers in source order; x12,y11,state12. No discarded List initializer oracle.'),
'bytes':('tests/conformance/bytes/program.min',[2,18],'Bytes initialized/indexed and one copied slice read; no subsequent copy independence mutation.'),
'bytes-alias':('tests/conformance/bytes/program.min',[22,27],'Bytes held in record/List is shared; mutations observed through original record.'),
'bounds':('tests/list-access.py',[47,66],'Empty/nonempty List reads/writes at length and extreme indices expect existing bounds diagnostic. No sentinel slot.'),
'nothing':('tests/regressions.py',[204,207],'Nothing rejected as field, parameter and List element; source diagnostics only.'),
'alias':('tests/ownership.py',[88,98],'List alias/self assignment plus immutable old Text survival after replacement. Does not assert deep List copying.'),
'param':('tests/readonly-parameters.py',[40,54],'Shared List parameter update/append exposes length2 and values6,6. Scalars are not addressable arguments.'),
'branch':('tests/regressions.py',[191,194],'Ordinary Boolean branches return42/7; terminal fail branch and bare return. Different exact count oracles.'),
'scope':('tests/conformance/bindings-and-scope/program.min',[1,7],'Branch-local shadow prints20, then outer11. Related lexical binding coverage.'),
'sibling':('tests/peer-research-swift-statements.py',[30,44],'Reject branch-local names in sibling branches and non-Boolean conditions. No Go initializer clause syntax.')}
coverage={k:dict(path=v[0],lines=v[1],extent=v[2],verification='source_read_only; not_executed') for k,v in C.items()}
# Each entry below is authored after reading the complete named body and helpers.
# Tuple layout: declaration line, disposition P(runtime subset pending)/I(incompatible), per-site expectations, compatibility, coverage IDs, proposal IDs.
D=[
(311,'P',[(317,'storage[0].term=1'),(319,'after element replacement storage[0].term=123')],'A local initialized List of explicit scalar records preserves these reads/replacements. Container-level mutable storage and array repetition are omitted; replacement is not a record copy proof.',['record','capture'],['P1']),
(331,'I',[(343,'scalar byte=101 after writable slice increments it')],'Minyar scalar arguments/bindings are values, not addressable storage convertible to a one-element array/slice. A shared one-element List control is original, not this scalar aliasing contract.',['param'],['P1']),
(350,'I',[(356,'first comptime by-value array call returns1'),(357,'second comptime by-value array call returns1')],'No compile-time function evaluation or by-value fixed arrays. Ordinary repeated List reads preserve values only, with shared argument semantics.',['literal'],[]),
(360,'P',[(367,'runtime initialized one-element slice[0]=2')],'A List literal [two] captures Integer2. Exclude pointer-to-array coercion, i32 and slice representation.',['literal'],['P2']),
(370,'P',[(382,'foo element0=1'),(383,'foo element1=2'),(384,'foo element2=3'),(387,'foo2 Boolean trash=true'),(388,'foo2 element0=1'),(389,'foo2 element1=2'),(390,'foo2 element2=3')],'Pass [1,2,3] and [1,two,3] to typed List parameters, separately with a true Boolean argument. Four helper calls per entry exercise both helper variants; each entry also runs comptime upstream, excluded here. No by-value or lifetime claim follows from scalar reads.',['literal','param'],['P2']),
(397,'P',[(418,'cases2 outer length2'),(419,'cases2 row0 length1'),(420,'cases2[0][0]=1'),(421,'cases2 row1 length2'),(422,'cases2[1][0]=2'),(423,'cases2[1][1]=3'),(437,'check outer length3'),(438,'check case0 length1'),(439,'check case0 row0 length1'),(440,'check[0][0][0]=1'),(441,'check case1 length1'),(442,'check case1 row0 length2'),(443,'check[1][0][0]=2'),(444,'check[1][0][1]=3'),(445,'check case2 length2'),(446,'check case2 row0 length1'),(447,'check[2][0][0]=4'),(448,'check case2 row1 length3'),(449,'check[2][1][0]=5'),(450,'check[2][1][1]=6'),(451,'check[2][1][2]=7')],'Typed nested Integer Lists preserve every length and leaf read. check is called on cases and cases3 (latter includes runtime two=2); cases2 is separately checked. Entry runs runtime and comptime upstream. Nested read oracles establish no alias/copy behavior.',['literal','nested','fresh'],['P3']),
(458,'P',[(473,'array[0].a=3'),(474,'array[0].b=4'),(475,'array[1].a=2'),(476,'array[1].b=3')],'Minyar requires explicit named constructors and all fields: Foo{a:3;b:4}, Foo{a:2;b:3}. Values project; field defaults/anonymous coercion/usize/fixed-size/comptime do not.',['record','fields'],['P1']),
(483,'I',[(490,'constant index4 reads sentinel0'),(493,'runtime index len=4 reads sentinel0')],'A length4 Minyar container rejects index4. Adding zero as a fifth ordinary element changes length and cannot reproduce sentinel access.',['bounds'],['P4']),
(500,'P',[(508,'true index selection reads0xAA=170'),(510,'false index selection reads0x55=85')],'Use an explicit Integer index assigned by an ordinary Boolean if/else, then index an Integer List. No conditional expression, u8 coercion or comptime typing claim.',['branch','literal'],['P2']),
(518,'I',[(532,'extern struct raw-byte length3 including zero-length array sentinel'),(533,'raw byte0=0x55'),(534,'raw byte2=0xAA')],'Minyar has no extern struct ABI or exposed raw record storage/sentinel. Three Bytes values would erase the layout contract.',['bytes'],[]),
(542,'I',[(561,'recursive zero-sized array container default x=0')],'Recursive records/empty recursive Lists exist, but no type-valued generic factory, @This, zero-sized inline array, defaults or undefined initialization. An empty recursive construction is related coverage, not this layout/type-resolution contract.',['empty'],[]),
(564,'I',[(582,'scalar arr1[0]=42'),(583,'scalar arr1[1]=56'),(584,'scalar arr1[2]=54'),(590,'union arr2[0].a=42'),(591,'union arr2[1].b=true'),(592,'union arr2[2].c contents=hello')],'Integer List [42,56,54] projects the scalar half only. Core anonymous heterogeneous tuple coercion and untagged union variants are absent; do not replace the union with unrelated record fields and claim compatibility.',['literal','record'],['P2']),
(599,'I',[(601,'array element0 is type u32'),(602,'array element1 is type i32')],'Minyar types are not stored values; no List<type>, reflection or comptime-only element type. Integer values cannot port this assertion.',['reject'],[]),
(605,'I',[(613,'tuple-coerced sentinel array element0=1; sentinel is not explicitly read')],'Absent tuple coercion and sentinel array types. Content-only [1,2,3] is not a sentinel validation; no missing sentinel assertion is invented.',['literal'],[]),
(616,'P',[(632,'pair initially exactly[1,2]'),(634,'direct initialized assignment yields exactly[3,4]'),(636,'temporary initialized assignment yields exactly[5,6]')],'Use a local owner record with a List<Integer> field and helper replacement, comparing length and each scalar explicitly. No List equality, mutable module globals, noinline promise or by-value copy. Save old alias as an original lifetime control.',['record','capture'],['P1']),
(639,'I',[(646,'byte reinterpretation at2=0x99'),(647,'byte reinterpretation at3=0x99')],'Sentinel0x9999 is stored after runtime u16 value300; both its bytes equal0x99 regardless byte order. Minyar exposes neither sentinel layout nor pointer reinterpretation. Explicit Bytes serialization would be original and unnecessary to this review.',['bytes'],[]),
(650,'P',[(657,'second repeated inner array element1=11')],'Initialize two length10 Integer Lists of11 and check selected cell. Upstream value read does not itself assert repetition copy independence. Deliberate shared versus separately constructed rows need independent controls.',['nested','fresh'],['P3']),
(660,'I',[(662,'array .ptr equals cast many-item pointer'),(663,'ptr[0]=10'),(664,'ptr[1]=20'),(665,'ptr[2]=30'),(666,'ptr[3]=40'),(667,'pointer-to-ptr dereference index4=50')],'No pointer .ptr field, pointer equality, pointer cast or pointer-to-pointer access. List reads10..50 omit the central pointer contract.',['literal'],[]),
(670,'P',[(685,'discarded literal still invokes helper twice; x=2')],'Use a shared Integer state List, a helper increments it and returns0, and an unused let value=[helper(state),helper(state)]. Existing syntax preserves required effects, excluding scalar address, intCast/u16-to-u8 and result-location lowering. This assertion checks count, not call order; add distinct ordered effects as an original extension.',['literal','effects'],['P5']),
(688,'P',[(694,'record-held array length2'),(695,'element0=10'),(696,'element1=20')],'Explicit owner record field List<Integer>=[10,20] preserves values/length. No anonymous record, context-dependent intCast, u16 or no-result-location contract.',['record','literal'],['P2']),
(699,'I',[(708,'each of32 zero-bit u0 elements equals0 after pointer iteration writes0')],'Minyar has signed64 Integers and no zero-bit numeric storage or element pointers. A32-zero List uses real storage and validates a different contract.',['nothing','reject'],[]),
(711,'P',[(722,'helper result123 equals input x123')],'Pass [x] to a List<Integer> helper returning element0. u64-to-u32 inferred cast and value-array calling convention excluded.',['literal'],['P2']),
(725,'P',[(747,'initialized array exactly[1,2,4,8]'),(748,'side_effects equals u4 maximum15')],'Helpers update shared state by1,2,4,8 and return those values into an Integer List. Check all values and state15. Exclude block expressions, u4/comptime result knowledge and array equality. Count/sum alone does not prove order; a decimal trace is an original extension.',['literal','effects'],['P5']),
(751,'P',[(763,'slice length4 and elements exactly[123,456,123,456]')],'Typed Integer List preserves ordered values. intCast/truncate are identities on these chosen small values; the test supplies no truncation boundary oracle. Exclude u16 coercion and array-to-slice reference.',['literal'],['P2']),
(766,'I',[(778,'slice length4, values[123,456,123,456], expected and actual in-memory sentinel999')],'expectEqualSentinel additionally reads index length via imported helper. Minyar lacks sentinel storage; contents-only port loses that assertion and width coercion.',['literal','bounds'],[]),
(781,'I',[(794,'many-pointer[0]=123'),(795,'many-pointer[1]=456'),(796,'many-pointer[2]=123'),(797,'many-pointer[3]=456')],'Core many-item pointer result typing absent. Scalar List projection can share P2, but does not validate pointers or @truncate.',['literal'],['P2']),
(800,'I',[(813,'sentinel many-pointer[0]=123'),(814,'sentinel many-pointer[1]=456'),(815,'sentinel many-pointer[2]=123'),(816,'sentinel many-pointer[3]=456'),(817,'sentinel many-pointer[4]=999')],'Length4 Minyar List rejects index4; ordinary fifth element would change the shape. Many-item pointers and u16 result typing absent.',['literal','bounds'],[]),
(820,'I',[(832,'pointer-array length4 and values[123,456,123,456]')],'No pointer-to-array result type. Runtime content projection is P2, with pointer coercion/width inference explicitly excluded.',['literal'],['P2']),
(835,'I',[(847,'pointer sentinel-array length4, values[123,456,123,456], in-memory sentinel999')],'Sentinel helper checks both content and index4 storage; pointer array and sentinel ABI absent.',['bounds','literal'],[]),
(850,'I',[(858,'tuple first item12345'),(859,'tuple second pointer converted to address0x1000')],'Heterogeneous tuple, pointers, integer-address conversion and inferred cast unsupported. A two-Integer record would remove pointer semantics.',['record'],[]),
(862,'I',[(872,'captured by-value row a[1] remains0 after source x[0][1] becomes15')],'Plain Minyar let a=x[0] shares the row and would observe15. Explicit copying into a fresh List can preserve0, but is an original snapshot algorithm, not by-value assignment. Initialize every Minyar cell; upstream only observes initialized selected cell.',['alias','fresh','capture'],['P6']),
(875,'I',[(893,'union-held record array bytes spell12345')],'No untagged union, inline string-to-array copying, or undefined scalar field. Explicit initialized owner record/Text preserves contents only, not this storage path.',['record'],[]),
(896,'I',[(914,'union-held non-sentinel destination array length5 and values[1,2,3,4,5]')],'Sentinel source coerces into plain array held inside union; no sentinel, union or inline copy counterpart. The destination expectation does not read the source sentinel.',['record','literal'],[]),
(917,'P',[(937,'runtime nested struct-array helper returns15'),(938,'comptime same helper returns15')],'Nested List<List<Cell>> with explicit Cell{x:15} preserves runtime return15; compile-time storage, by-value arrays and u8 excluded. No aliasing assertion here.',['record','nested'],['P3']),
(941,'P',[(952,'global nested array first inner length1'),(953,'first nested string=hello')],'Local List<List<Text>> [[hello],[world,hello]] preserves checked length/value. Despite test title, call sites shown are ordinary testing calls; global const construction/comptime storage excluded, not counted as explicit comptime assertions. Other leaves not asserted upstream can be original controls.',['literal'],['P3']),
(956,'I',[(977,'copied nested union variant D=1')],'Nested tagged unions, tags and padding layout are absent. Integer record fields would remove the core layout bug class.',['record'],[]),
(980,'I',[(989,'result index=0'),(990,'result stored void value equals empty void literal')],'Nothing cannot be stored in a record or List; runtime indexing of zero-bit void and anonymous record unsupported. Index0 alone does not preserve second assertion.',['nothing'],[]),
(993,'P',[(1001,'all10 u32 elements equal123; separately all10 Foo records compare field x=10')],'Scalar Integer fill can preserve123. Explicit newly constructed Cell{x:10} values with field checks preserve record contents, excluding record equality, generic @splat, widths and comptime. Reusing one Cell shares in Minyar; independent mutation/sharing controls are original, because upstream equality alone proves no alias rule.',['fresh','record'],['P7']),
(1014,'I',[(1023,'all10 numeric elements100; separately all10 optional opaque pointers address0x1000'),(1026,'numeric sentinel42; optional pointer sentinelnull at index10')],'Sentinel, optional opaque pointers/address conversion, generic splat and comptime absent. Scalar fill is related P7 only, not this sentinel contract.',['bounds'],['P7']),
(1037,'I',[(1049,'zero-length array is comptime-known with sentinel42; pointer variant sentinelnull')],'Zero-length array splat of runtime undefined value still supplies a compile-time sentinel. Minyar typed empty Lists have no slot0 and no runtime-undefined/comptime notion.',['empty','bounds'],['P4']),
(1060,'I',[(1062,'empty referenced array coerces to slice of comptime length0')],'Runtime empty List length0 is related but cannot validate compile-time pointer/slice coercion.',['empty'],['P4']),
(1065,'I',[(1066,'reference to empty array accepted as many-item pointer'),(1067,'pointer discarded; no value assertion')],'No pointer type or empty anonymous array coercion. This is compile-acceptance only, not a hidden value test.',['empty'],[]),
(1070,'I',[(1072,'empty sentinel slice comptime length0'),(1073,'sentinel slice slot0=0 at comptime')],'Minyar emptiness and bounds contrast must remain distinct; no sentinel slot0 or comptime.',['empty','bounds'],['P4']),
(1076,'I',[(1078,'empty sentinel many-pointer slot0=0 at comptime')],'No many-pointer/sentinel/comptime. Ordinary empty container access stops; replacing with [0] changes length.',['bounds'],['P4']),
(1081,'I',[(1087,'anytype helper reports exact type of empty-array-reference initializer')],'No generic anytype, type-valued result, type reflection or compile-time assertion. Typed empty List context is not equivalent.',['empty'],[]),
(1090,'I',[(1100,'loaded opaque-pointer cast has exact empty tuple type at comptime; no value assertion')],'No opaque pointer, alignment cast, pointer cast, empty tuple or type reflection. Empty runtime List has a different contract.',['empty'],[]),
(1103,'I',[(1112,'runtime-known array data slot0=42'),(1113,'sentinel storage slot1=123')],'No sentinel array or many-pointer access. A List of length1 reads42 but rejects index1; adding ordinary123 changes length.',['bounds','literal'],['P4']),
(1116,'I',[(1125,'generic error-union/optional vector splat call succeeds and result discarded'),(1126,'generic error-union/optional fixed-array splat call succeeds and result discarded')],'No error union, optional, vector, generic type-valued argument or @splat. No payload element/assertion is present; do not claim four ones were checked.',['reject'],[]) ]
U=[]
for idx,(start,disp,expect,compat,cov,prop) in enumerate(D,21):
 end=closing(zig,start); name=re.match(r'test "(.*)"',zig[start-1]).group(1)
 helpers=[]
 for line in range(start,end+1):
  m=re.search(r'\bfn (\w+)\(',zig[line-1])
  if m: helpers.append(dict(name=m.group(1),path='test/behavior/array.zig',lines=[line,closing(zig,line)]))
 if start==331:helpers.append(dict(name='testImplicitCastSingleItemPtr',path='test/behavior/array.zig',lines=[339,344]))
 if start==350:helpers.append(dict(name='testArrayByValAtComptime',path='test/behavior/array.zig',lines=[346,348]))
 body='\n'.join(zig[start-1:end]); guards=re.findall(r'builtin.zig_backend == \.(\w+)',body)
 refs=['docs/language.md','docs/runtime-memory.md']
 unit=dict(id=f'Z{idx}',language='zig',path='test/behavior/array.zig',lines=[start,end],upstream_unit=name,source_url=source['test/behavior/array.zig']['url']+f'#L{start}-L{end}',grouped_scope=True,grouping='One named test, all helper bodies and assertion cases grouped; no assertion/helper port credit.',review_status='semantically_reviewed',upstream_expectations=[dict(lines=[l],expected=e) for l,e in expect],helpers_read=helpers,backend_skip_guards_read=guards,backend_skip_disposition='Expected assertions apply only when upstream backend guards allow test body; no backend executed.',comptime_call_sites=[line for line in range(start,end+1) if 'comptime ' in zig[line-1] and not re.search(r'\bfn\b',zig[line-1])],disposition='runtime_adaptation_pending' if disp=='P' else 'incompatible_as_written',minyar_compatibility=compat,local_coverage_ids=cov,proposed_regressions=prop,port_status='not_implemented; not_executed',pending_original_port_rationale='See proposal(s) '+','.join(prop)+': original existing-syntax control only; unsupported peer contracts remain excluded.' if prop else 'No original port proposed: the selected core contract is absent, or related source coverage already illustrates its supported runtime portion.',minyar_contract_references=refs)
 U.append(unit)
# Complete errorcheck Go file: every positive block and every ERROR case.
A=[(23,27,'Mutex value assignment',[(25,'accepted assignment of sync.Mutex values'),(26,'blank discard accepted')],'No sync.Mutex/native lock type. Minyar ordinary record assignment aliases, whereas Go struct assignment copies.',['record'],[]),
(28,32,'embedded record assignment',[(30,'accepted assignment of T embedding int and sync.Mutex'),(31,'blank discard accepted')],'No embedded fields or native lock; named record assignment shares rather than copies.',['record'],[]),
(33,37,'Mutex array assignment',[(35,'accepted assignment of [2]sync.Mutex values'),(36,'blank discard accepted')],'No fixed arrays of sync.Mutex; List assignment shares.',['alias'],[]),
(38,42,'embedded record array assignment',[(40,'accepted assignment of [2]T values'),(41,'blank discard accepted')],'No embedded/native lock fields or by-value array copying.',['record','alias'],[]),
(43,46,'unexported Time composite literal',[(44,'compiler diagnostic regex assignment.*Time')],'Foreign library internals, positional struct literal and nil unsupported. Minyar missing named fields is a different diagnostic class.',['fields'],[]),
(47,50,'unknown/private Mutex field literal',[(48,'compiler diagnostic regex (unknown|assignment).*Mutex')],'sync.Mutex internals are not Minyar records. Existing unknown-field diagnostics provide related original compiler coverage; do not import this library-specific regex.',['fields'],[]),
(51,58,'pointer dereference assignment',[(52,'empty Mutex constructor address accepted'),(53,'Mutex local declaration accepted'),(54,'dereference-to-value assignment accepted'),(55,'value-to-dereference assignment accepted'),(56,'x discard accepted'),(57,'y discard accepted')],'No address-taking or dereference. A List-held explicit record replacement is an original shared-reference control, not by-value Mutex assignment.',['record'],['P1']),
(59,66,'repeated short declaration with outer x',[(62,'compiler regex .*x.* repeated on left side of :=|x redeclared in this block')],'No multi-target := declaration; replacing with two sequential let declarations changes the diagnostic question. Branch shadowing is separately supported.',['scope'],[]),
(67,70,'repeated short declaration without outer a',[(68,'compiler regex .*a.* repeated on left side of :=|a redeclared in this block')],'No multi-target := declaration. The Go duplicate target contract is not a request to change Minyar same-scope binding semantics.',['scope'],[])]
for i,(start,end,name,expect,compat,cov,prop) in enumerate(A,1):
 U.append(dict(id=f'A{i}',language='go',path='test/assign.go',lines=[start,end],upstream_unit=name,source_url=source['test/assign.go']['url']+f'#L{start}-L{end}',grouped_scope=True,grouping='One complete main lexical block; all accepted assignments or error annotations grouped.',review_status='semantically_reviewed',upstream_expectations=[dict(lines=[l],expected=e) for l,e in expect],helpers_read=[],disposition='incompatible_as_written',minyar_compatibility=compat,local_coverage_ids=cov,proposed_regressions=prop,port_status='not_implemented; not_executed',pending_original_port_rationale='P1 only as explicit initialized Minyar shared-reference control.' if prop else 'No direct port: core Go syntax/library/type contract absent; related local fixtures are source-only coverage.',minyar_contract_references=['docs/language.md','docs/runtime-memory.md']))
I=[(24,28,1,'literal true','Ordinary Boolean if plus Integer increment directly preserves1.'),(30,34,0,'literal false','Ordinary false branch remains skipped; preserves0.'),(36,40,1,'true with initializer','Use explicit enclosing function/local one=1 before if; exclude Go initializer scope syntax.'),(42,47,0,'false with initializer','Initialize local one before false branch; preserves0; initializer execution itself is not asserted upstream.'),(49,53,1,'comparison condition','Integer5<7 is Boolean true; preserves1.'),(55,61,1,'true else','Only true arm increments; preserves1.'),(63,69,-1,'false else','Only else arm decrements; preserves-1.'),(71,80,-1,'initializer and body shadow','Explicit local t=1 available to both branches; inner t=7 in skipped true arm. Exclude initializer clause extent; do not leak a true-arm binding into else.'),(82,92,-1,'outer binding and body shadow','Outer t=1 is used by else while skipped true arm declares distinct t=7. Existing lexical scopes preserve-1.')]
for i,(start,end,value,name,compat) in enumerate(I,1):
 U.append(dict(id=f'I{i}',language='go',path='test/if.go',lines=[start,end],upstream_unit='main: '+name,source_url=source['test/if.go']['url']+f'#L{start}-L{end}',grouped_scope=True,grouping='One main branch scenario and its assertequal call.',review_status='semantically_reviewed',upstream_expectations=[dict(lines=[end],expected=f'count={value}; assertequal succeeds silently')],helpers_read=[dict(name='assertequal',path='test/if.go',lines=[11,16])],disposition='runtime_adaptation_pending',minyar_compatibility=compat+' No panic or Go diagnostic port.',local_coverage_ids=['branch','scope','sibling'],proposed_regressions=['P8'],port_status='not_implemented; not_executed',pending_original_port_rationale='P8 gives all exact count oracles; enclosing local/function scope replaces absent initializer clause without changing language semantics.',minyar_contract_references=['docs/language.md']))
P=[
('P1','Shared explicit records and replacement','Use explicit initialized Cell records in local List and owner record; check1 then123 after replacement, and owner List values[1,2],[3,4],[5,6] across direct and helper replacement. Construct Foo values(3,4),(2,3) explicitly. Keep old element/List alias across replacement and observe its unchanged old value.','1,123; ordered pairs1,2 then3,4 then5,6; Foo fields3,4,2,3; saved old element1 and old pair1,2 survive.','Related records/replacement lifetime fixtures exist; exact peer values and full/temporary replacement sequence are pending. No implicit copies, globals, defaults or pointers.'),
('P2','Literal arguments, contextual indexing and ordered values','Use literal and runtime two=2 in List argument helpers, with and without Boolean true; check every1,2,3. Check scalar lists[42,56,54], one-element2, owner[10,20], helper123 and[123,456,123,456]. Select index via ordinary if from true/false and read170/85.','Exact lengths and every scalar as listed; helper reads123; selected values170,85.','Source literal/effect/parameter fixtures already cover related syntax. New values are original runtime projections; no width truncation boundary, tuple, pointer or compile-time inference claim.'),
('P3','Ragged nested values and explicit sharing controls','Build typed nested cases [[[1]],[[2,3]],[[4],[5,6,7]]], plus cases2 [[1],[2,3]]. Check all peer lengths/leaves. Build two separately initialized rows of ten11s and a separate deliberately shared-row control; mutate one and distinguish independent from shared rows. Read nested Cell15 and Text rows[hello],[world,hello].','All ragged lengths/leaves in Z26; selected repeated value11; mutation affects only fresh row, both shared positions; Cell15 and first Text row length1/hello.','Existing dynamic row independence and nested read fixtures do not cover this exact ragged topology/shared contrast. Mutation controls are original additions, not inferred upstream copy assertions.'),
('P4','Empty runtime containers and no sentinel','Reuse typed empty Integer List/Bytes length0 and negative index-at-length contracts; if future Bytes companion is needed inspect its diagnostic fixtures first. For runtime initialized length1 value42, index1 remains invalid.','Runtime empty lengths0; List index0/length stops with current bounds diagnostic; length1 value42 is valid only at0.','Existing empty/bounds source fixtures cover the List contract. No redundant port or new diagnostic proposed without a concrete gap; sentinel comparisons remain incompatible.'),
('P5','Unused initializer effects and ordered trace','A helper on shared Integer state increments then returns0; bind an unused List containing two calls and check state2. Separately four helpers add1,2,4,8 and return each value; check exact list and state15. Add decimal trace for order1,2,3,4, so order is independently observed.','Unused literal state2; [1,2,4,8], state15, ordered trace1234.','Existing used literal and record effects cover left-to-right execution; unused literal effect preservation and exact weighted trace remain narrow original additions. Upstream state2/15 alone does not assert ordering.'),
('P6','Shared row binding versus explicit snapshot','Start initialized nested rows with chosen slot0; bind alias=x[0]; create fresh copied row by explicit scalar iteration into a new Integer List before mutation; set source chosen slot15. Check alias15, explicit snapshot0. Replace the source outer position, drop local source references, and check retained alias15/snapshot0.','Plain alias15; fresh snapshot0; both retained values remain15/0 after source replacement.','Zig asserts0 from an implicit value copy; this Minyar contrast follows current shared ownership. Existing dynamic independent rows/managed projection capture are related, but do not assert this exact alias-versus-explicit-snapshot contrast.'),
('P7','Scalar filling and record construction versus sharing','Fill ten Integer values123. Construct ten fresh Cell{x:10} records and check fields individually; separately add the same Cell ten times, mutate its x and observe all entries. Mutation of one fresh cell must preserve other fresh cells.','Ten123 values; ten initial fields10; one fresh mutation affects only its cell; one deliberately shared record mutation affects every shared position.','Upstream structural equality does not assert alias independence. Minyar record equality unsupported, so field checks and explicit construction/sharing are required; no splat operator, generics or comptime.'),
('P8','Exact branch counts and scoped explicit initializer','Preserve all Go if.go count oracles in ordinary Minyar if/else. Put initializer values in an explicit helper/local scope; check outer t1 remains1 while branch-local t7 is available only in its own arm. An original effectful initializer can count one call before a false condition; no initializer-clause syntax is added.','Counts1,0,1,0,1,1,-1,-1,-1; outer t1; optional original initializer call count1.','Existing branch-return, shadow and sibling rejection fixtures cover related behavior; exact count sequence is pending. Effectful initializer is an original extension, not an upstream assertion.')]
proposals=[dict(id=i,name=n,original_regression=o,expected=e,existing_gap=g,status='proposal_only; not_implemented; not_executed') for i,n,o,e,g in P]
review=dict(schema='minyar.peer_readonly_go_zig.review.v2',created_utc=now,mode='read_only_sources; author_owned_research_records_only',scope=dict(zig=dict(commit=source['test/behavior/array.zig']['commit'],path='test/behavior/array.zig',new_reviewed_lines=[310,1127],prior_reviewed_lines=[1,309],prior_record='research/2026-10-memory/peer-readonly-go-zig-round2.json',combined_extent='complete_file_across_round2_and_round3; no_duplicate_prefix_credit',unreviewed_lines=None),go=dict(commit=source['test/assign.go']['commit'],complete_files={'test/assign.go':[1,71],'test/if.go':[1,93]}),support='Selected standard assertion helper bodies only; full support files retained but their tests/remainder unreviewed and uncounted.',other_paths='Unselected peer files/directories remain unreviewed. Prior restricted Rust resource not retried or routed around.'),grouping_policy='One named Zig test including all assertions/helpers, one Go errorcheck lexical block, or one Go if scenario. Grouped explicitly; no assertion/helper or listing promoted to test/port.',upstream_outcome_policy='Pinned source expectations only. array.zig assertions conditional on backend skip guards; assign.go is errorcheck and must not compile with four matching error annotations alongside accepted assignments; if.go //run expects silent success. Nothing executed.',local_coverage_policy='Inspected source ranges/hashes only; no executed/passing status. Exact gap is relative to listed source fixtures, not exhaustive repository absence.',ownership_policy='Existing simple syntax, automatic ownership and shared reference semantics preserved. No memory syntax, pointer/view/sentinel/tuple/type features proposed.',evidence='evidence/peer-readonly/go-zig-round3/provenance.json',local_coverage_references=coverage,units=U,proposed_regressions=proposals,resource_dispositions=[dict(resource='prior restricted Rust URL',status='excluded_not_retried',reason='Caller explicitly prohibited retry/routing around.'),dict(resource='previously stopped integration/literature lanes',status='excluded_not_resumed',reason='Read-only independent research only; no tests/compiler/build/tooling.'),dict(resource='tests/conformance/booleans/program.min',status='optional_local_candidate_missing_skipped',reason='Search candidate absent; actual branch fixtures read instead.')],prohibited_actions_executed=[],new_unavailable_upstream_resources=[],content_or_service_restriction_this_round=None)
counts=dict(selected_test_source_entries=len({u['path'] for u in U}),complete_new_files_reviewed=2,continued_files_completed_across_rounds=1,zig_named_test_groups=sum(u['language']=='zig' for u in U),go_errorcheck_groups=sum(u['path']=='test/assign.go' for u in U),go_branch_groups=sum(u['path']=='test/if.go' for u in U),authored_comparison_groups=len(U),dispositions=dict(collections.Counter(u['disposition'] for u in U)),proposed_regressions=len(proposals),ports_implemented=0,peer_or_local_test_executions=0)
review['counts']=counts
review['ledger_handoff']=dict(central_manifests_changed=False,merge_policy='Add round3 grouped units; union Zig reviewed extents1..309 and310..1127 at matching source hash. Do not count continued Zig path as newly distinct, or re-add round2 prefix groups.',complete_selected_paths=['test/behavior/array.zig','test/assign.go','test/if.go'],selected_remaining_source_review_pending=[],selected_ports_pending='All runtime_adaptation_pending groups and proposed originals remain unimplemented/unexecuted; incompatible peer core contracts excluded.')
# Library oracle helpers are support, not newly selected tests or whole-file semantic reviews.
H=[('lib/std/testing.zig','expectEqual',[73,76]),('lib/std/testing.zig','expectEqualInner',[78,218]),('lib/std/testing.zig','expectEqualSlices',[363,377]),('lib/std/testing.zig','expectEqualSentinel',[564,602]),('lib/std/testing.zig','expect',[606,608]),('lib/std/testing.zig','expectEqualStrings',[648,675]),('lib/std/meta.zig','eql',[707,765]),('lib/std/meta.zig','hasUniqueRepresentation',[1108,1151]),('lib/std/mem.zig','eql',[693,707]),('lib/std/mem.zig','eqlBytes',[729,787]),('lib/std/mem.zig','indexOfDiff',[791,798]),('lib/std/mem.zig','sliceAsBytes',[4344,4357]),('lib/std/debug.zig','assert',[558,560])]
review['imported_oracle_helpers_read']=[dict(path=p,name=n,lines=ls,source_url=source[p]['url']+f'#L{ls[0]}-L{ls[1]}',meaning='Direct oracle/helper body inspected, not a reviewed test group; diagnostic formatting/transitive utility internals not exhaustive.') for p,n,ls in H]
for u in U:
 if u['language']=='zig':
  alltext='\n'.join(zig[u['lines'][0]-1:u['lines'][1]])
  for h in u['helpers_read']: alltext+='\n'+'\n'.join(zig[h['lines'][0]-1:h['lines'][1]])
  names=[]
  for n in ['expectEqualSentinel','expectEqualStrings','expectEqualSlices','expectEqual','expect','assert']:
   if re.search(r'\b'+n+r'\(',alltext):names.append(n)
  if 'mem.eql(' in alltext:names.append('mem.eql')
  u['imported_oracle_helper_names']=names
  u['runtime_and_comptime_driver_lines']=[i for i in range(u['lines'][0],u['lines'][1]+1) if re.search(r'try (comptime )?(S\.|testImplicit)',zig[i-1])]
# Snapshot referenced local files. Read manifests/prior records were already captured at start.
localsnap=[]
for p in sorted({v['path'] for v in coverage.values()}|{'docs/language.md','docs/runtime-memory.md'}):
 data=(ROOT/p).read_bytes();localsnap.append(dict(path=p,sha256=hashlib.sha256(data).hexdigest(),bytes=len(data),lines=len(data.splitlines()),snapshot_utc=now,meaning='source_provenance_not_execution'))
(E/'local-coverage-snapshot.json').write_text(json.dumps(localsnap,indent=2)+'\n')
# Source spans add exact continuation hash, preserving CRLF/newline bytes.
for s in S:
 data=(ROOT/s['evidence_path']).read_bytes()
 if s['path']=='test/behavior/array.zig':
  s.update(semantic_review_lines=[310,1127],semantic_review_sha256=hashlib.sha256(b''.join(data.splitlines(keepends=True)[309:])).hexdigest(),extent='complete_remaining_file; combine_with_round2_prefix',license='MIT')
 elif s['path'] in ['test/assign.go','test/if.go']:s.update(semantic_review_lines=[1,s['lines']],extent='complete_selected_file',license='BSD-3-Clause')
 elif s['path']=='LICENSE':s.update(extent='complete_license_read',license='MIT' if s['language']=='zig' else 'BSD-3-Clause')
 else:s.update(semantic_review_spans=[ls for p,n,ls in H if p==s['path']],extent='selected_support_helper_bodies_only; rest_unreviewed',license='MIT')
(E/'sources.json').write_text(json.dumps(S,indent=2)+'\n')
# Bind every comparison to exact source/license hashes and relevant documented contract spans.
for u in U:
 u['source_sha256']=source[u['path']]['sha256']
 u['source_commit']=source[u['path']]['commit']
 u['license_sha256']=next(x['sha256'] for x in S if x['path']=='LICENSE' and x['language']==u['language'])
 u['minyar_contract_references']=[dict(path='docs/language.md',lines=[134,160],meaning='Homogeneous initialized Lists and documented shared-reference behavior'),dict(path='docs/language.md',lines=[253,277],meaning='Named explicit record fields, shared records and lack of record equality'),dict(path='docs/runtime-memory.md',lines=[19,73],meaning='Recursive construction and conservative shared-reference cycle prevention')]
 if u['path']=='test/if.go':u['minyar_contract_references']=[dict(path='docs/language.md',lines=[3,15],meaning='Lexical bindings and assignments'),dict(path='docs/language.md',lines=[98,99],meaning='Boolean-only conditions'),dict(path='docs/language.md',lines=[299,309],meaning='Ordinary if/else if chains')]
 if 'nothing' in u['local_coverage_ids']:u['minyar_contract_references'].append(dict(path='docs/language.md',lines=[320,323],meaning='Nothing is return-only, not a stored value'))
(R/'peer-readonly-go-zig-round3.json').write_text(json.dumps(review,indent=2)+'\n')
print(json.dumps(counts,indent=2))
