"""Render authored research ledger/report and preserve provenance; no test/build execution."""
import json,hashlib,datetime
from pathlib import Path
root=Path.cwd();e=root/'evidence/peer-readonly/go-zig-round3';r=root/'research/2026-10-memory';j=json.loads((r/'peer-readonly-go-zig-round3.json').read_text());c=j['counts'];q=json.loads((e/'document-checks.json').read_text());sources=json.loads((e/'sources.json').read_text());prior=json.loads((r/'peer-readonly-go-zig-round2.json').read_text());oldprov=json.loads((root/'evidence/peer-readonly/go-zig-round2/provenance.json').read_text())
union={}
for u in prior['units']+j['units']:union[(u['language'],u['path'],u['id'])]=u
handoff=dict(round3_counts=c,combined_round2_round3_selected_scope=dict(authored_comparison_groups=len(union),distinct_test_source_paths=len({(u['language'],u['path']) for u in union.values()}),complete_selected_test_files=len({(u['language'],u['path']) for u in union.values()}),zig_named_test_groups=q['zig_complete_named_tests_across_rounds'],dispositions={d:sum(u['disposition']==d for u in union.values()) for d in ['runtime_adaptation_pending','incompatible_as_written']},ports_implemented=0,execution_validations=0),pending=dict(selected_remaining_source_review=[],runtime_projection_unit_ids=[u['id'] for u in j['units'] if u['disposition']=='runtime_adaptation_pending'],original_control_proposals=[p['id'] for p in j['proposed_regressions']],incompatible_unit_ids=[u['id'] for u in j['units'] if u['disposition']=='incompatible_as_written'],unselected_peers='Unreviewed; no directory-exhaustiveness claim.',restricted_rust='Not retried or bypassed; unchanged explicit availability gap.'),ledger_merge='Central ledger unchanged. Merge authored grouped records and union exact same-hash Zig prefix/remainder; do not count assertions/helpers as ports or the continued path as a newly distinct file.')
(e/'handoff.json').write_text(json.dumps(handoff,indent=2)+'\n')
md=['# Read-only Go/Zig peer comparison — round 3','',f"Completed **{c['authored_comparison_groups']} new authored comparison groups**: {c['zig_named_test_groups']} remaining Zig named tests, {c['go_errorcheck_groups']} Go assignment blocks and {c['go_branch_groups']} Go branch scenarios. **{c['dispositions']['runtime_adaptation_pending']} runtime subsets remain pending; {c['dispositions']['incompatible_as_written']} groups are incompatible as written.** {c['proposed_regressions']} original-control proposals are recorded, with P4 explicitly reusing existing empty/bounds contracts unless a concrete Bytes gap is later found. **Zero ports and zero test executions.**",'',
'Every named test, assertion case and in-file helper in the selected remainder was read through EOF. This is semantic research, not test execution, a production defect finding or whole-directory coverage. The plain-language/shared-reference contract is preserved; no language or memory syntax changes are proposed.','',
'| Selected immutable source | Actual new semantic extent | Grouping |','| --- | --- | --- |']
for path,span,n in [('test/behavior/array.zig',j['scope']['zig']['new_reviewed_lines'],c['zig_named_test_groups']),('test/assign.go',j['scope']['go']['complete_files']['test/assign.go'],c['go_errorcheck_groups']),('test/if.go',j['scope']['go']['complete_files']['test/if.go'],c['go_branch_groups'])]:
 s=next(x for x in sources if x['path']==path);md.append(f"| [{path}]({s['url']}) | Physical raw-byte lines {span[0]}–{span[1]} | {n} authored groups |")
md+=['',f"Combined with the exact matching [round 2 record](peer-readonly-go-zig-round2.json), Zig array.zig is now completely reviewed: {q['zig_complete_named_tests_across_rounds']} named tests across the prefix and remainder. The newly selected Go files are complete. The [handoff ledger](../../evidence/peer-readonly/go-zig-round3/handoff.json) derives the union over selected files; it does not measure the whole campaign. Neither inventory discovery nor full-byte support-file retrieval receives semantic-review credit.",'',
'Go assign.go has an errorcheck directive: successful analysis means matching its ERROR annotations while accepting the positive assignment cases. It is not a successful executable program. Go if.go expects silent successful execution; Zig expectations apply only when the recorded backend guards permit its body. All outcomes here are inferred from primary source, never observed by running programs.','',
'Exact full-byte source/license hashes, review spans and continuation hash are in [provenance](../../evidence/peer-readonly/go-zig-round3/provenance.json). Immutable source snapshots and their license notices are retained beside it. Authoritative lines include blank lines; web display normalization is not used. [Structured records](peer-readonly-go-zig-round3.json) contain exact per-site expectations, helper spans, guards, contracts and coverage references.','',
'## Findings that affect a Minyar adaptation','',
'- **Copied rows differ from shared bindings.** Zig L862–873 explicitly checks a captured row element remains zero after the source changes to fifteen. Plain Minyar binding of the inner List would observe fifteen. P6 proposes an alias versus explicit fresh snapshot control using existing syntax; implicit copying is not added.',
'- **Sentinel checks include memory beyond logical length.** The imported expectEqualSentinel helper first compares contents and lengths, then reads the expected and actual sentinel slots. Numeric sentinel 999, empty sentinel zero and sentinel splat cases cannot become content-only ports. Minyar rejects access at length. The tuple-to-sentinel case L605–614 only reads element zero; no absent sentinel assertion is invented.',
'- **Effects need an independent oracle.** A discarded array initializer checks two helper calls; weighted initializers check values 1,2,4,8 and state fifteen. These counters do not prove order on their own. P5 separates unused-initializer count from an original decimal trace that checks order. Existing used List literal/record initializer tests are related source coverage.',
'- **Nested reads and structural comparisons do not prove copying.** Ragged nested lengths/leaves and scalar filling project cleanly. Zig record comparisons recurse through fields; Minyar has no record equality. P3/P7 use individual fields and deliberately distinguish fresh construction from repeated shared references.',
'- **Type, storage and diagnostic contracts stay excluded.** Zero-bit values, type-valued arrays, union padding, undefined storage, pointer casts, optional/error unions and comptime execution have no direct counterpart. The final optional/error-union splat test discards its payload and does not assert payload contents. Go sync.Mutex/Time and repeated short-declaration regexes are library/syntax-specific, not imported Minyar diagnostics.',
'- **Ordinary branches remain simple.** Complete Go if.go supplies exact count oracles; ordinary Minyar Boolean if/else supports the runtime values. Go initializer clauses are expressed with existing explicit locals/functions. Branch-local bindings must not leak into sibling branches.','',
'## Complete authored comparison groups','',
'Pending runtime subset identifies a bounded adaptation or value projection with unsupported contracts excluded; it does not mean the whole upstream test is compatible or ported. Incompatible as written means its core contract is absent or different. Helpers/assertion sites remain grouped, never extra tests or ports. Local coverage below means actual inspected fixture source only; gaps are relative to those fixtures, not an exhaustive repository claim.','']
for u in j['units']:
 a,b=u['lines'];label='Pending runtime subset' if u['disposition']=='runtime_adaptation_pending' else 'Incompatible as written'
 md += [f"**{u['id']} — [{u['path']}:{a}–{b}]({u['source_url']}) — {u['upstream_unit']}. {label}.**",'', 'Expected primary-source cases: '+ '; '.join('L'+','.join(map(str,x['lines']))+': '+x['expected'] for x in u['upstream_expectations'])+'.','',u['minyar_compatibility'],'']
 if u['helpers_read']:md+=['In-file helper bodies read: '+ '; '.join(f"{h['name']} L{h['lines'][0]}–{h['lines'][1]}" for h in u['helpers_read'])+'.','']
 if u.get('backend_skip_guards_read'):md+=['Upstream skips: '+', '.join(u['backend_skip_guards_read'])+'. No backend executed.','']
 if u.get('comptime_call_sites'):md+=['Explicit comptime-related source lines: '+', '.join(map(str,u['comptime_call_sites']))+'. Parameter/driver details remain in the pinned body.','']
 cs=[]
 for k in u['local_coverage_ids']:
  t=j['local_coverage_references'][k];a,b=t['lines'];cs.append(f"[{t['path']}:{a}–{b}](../../{t['path']}) — {t['extent']}")
 md+=['Inspected local coverage: '+' '.join(cs),'',u['pending_original_port_rationale'],'']
md+=['## Original existing-syntax controls','',
'All controls are proposals only, with exact expected values rather than observations. None implements a missing peer feature. P4 identifies related already-covered contracts and requires a demonstrated gap before new cases.','']
for p in j['proposed_regressions']:
 md += [f"**{p['id']} — {p['name']}.**",'',p['original_regression'],'','Expected: '+p['expected'],'',p['existing_gap'],'']
md+=['## Provenance and review limits','',
'| Immutable primary file | SHA256 | License |','| --- | --- | --- |']
for s in sources:md.append(f"| [{s['language']} {s['path']}]({s['url']}) | `{s['sha256']}` | {s['license']} |")
md+=['','Imported oracle helpers are selectively read support bodies in testing.zig, meta.zig, mem.zig and debug.zig, including sentinel and structural equality behavior. Their remaining implementation, standard-library tests and transitive diagnostic/utility machinery are not exhaustive reviews and receive no peer group credit. See the exact helper spans in the structured record.','',
'All selected upstream and supporting source/license fetches succeeded. No new upstream unavailability or content/service restriction occurred. The prior restricted Rust resource was neither retried nor routed around. Missing optional local booleans fixture was skipped; actual branch/scope fixtures supplied coverage. Stopped integration/literature execution lanes were not resumed.','',
f"[Record consistency checks](../../evidence/peer-readonly/go-zig-round3/document-checks.json) account for {q['zig_assertion_call_sites']} Zig assertion call sites, {q['zig_helper_bodies_attached']} attached in-file helper bodies, {q['go_error_annotation_sites']} Go error annotations and {q['go_if_assertion_sites']} Go branch assertion calls. These are grouped source sites, not execution counts. Checks verify names, spans, guards, exact hashes and ledger consistency without running any test/compiler/peer program.",'',
'Only peer-readonly-go-zig-round3.md/.json and evidence/peer-readonly/go-zig-round3 were authored. Existing dirty workspace was preserved by this lane. No production/build/test files, central manifests, commits, installations, compilation, timings, soak or application cohorts were changed or run. Current campaign work in other lanes may change unrelated files concurrently.','',
'No selected-file source review remains pending. All runtime projections and proposed original controls remain unimplemented/unexecuted; incompatible core contracts stay excluded. Unselected peer files remain unreviewed. Campaign completion remains the parent’s responsibility and retains its earliest authorized completion time in the campaign README.','']
(r/'peer-readonly-go-zig-round3.md').write_text('\n'.join(md))
# Preserve initial hashes and report any concurrent drift rather than overwriting history.
initial=json.loads((e/'local-initial-snapshot.json').read_text());coverage=json.loads((e/'local-coverage-snapshot.json').read_text());drift=[]
for s in initial+coverage:
 b=(root/s['path']).read_bytes();h=hashlib.sha256(b).hexdigest()
 if h!=s['sha256']:drift.append(dict(path=s['path'],original_sha256=s['sha256'],final_sha256=h,meaning='Concurrent observed reference change; not authored by this lane.'))
arts=[]
for p in [r/'peer-readonly-go-zig-round3.json',r/'peer-readonly-go-zig-round3.md',e/'document-checks.json',e/'handoff.json',e/'author_records.py',e/'check_records.py',e/'finalize_records.py']:
 b=p.read_bytes();arts.append(dict(path=str(p.relative_to(root)),sha256=hashlib.sha256(b).hexdigest(),bytes=len(b)))
prov=dict(schema='minyar.peer_readonly_go_zig.provenance.v2',recorded_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),selected_sources_and_licenses=sources,local_initial_snapshot=initial,local_coverage_snapshot=coverage,prior_exact_records=[x for x in initial if 'round2' in x['path']],workspace_status_snapshot='evidence/peer-readonly/go-zig-round3/workspace-initial-status.txt',ag_instruction='User-injected AGENTS instructions prohibit non-Conventional commit format; no filesystem AGENTS.md in workspace/ancestors found, no commits made.',overlap_check='Manifest/ledger and all research JSON path searches found assign.go/if.go listed but no prior authored review. Zig prefix overlap exists only in exact round2; continuation joins at same full hash.',line_policy='One-based physical raw-byte lines, including blank lines.',restrictions='Read-only primary/local source review; only owned research artifacts authored; no compiler/test/installation/production/build/test edits/commit/subagent/timing/integration resumption.',prohibited_actions_executed=[],content_or_service_restriction_this_round=None,new_unavailable_upstream_resources=[],resource_dispositions=j['resource_dispositions'],source_retention='Complete immutable upstream bytes retained as evidence .txt with adjacent pinned license notices; only selected test extents/support helper spans receive semantic-review credit.',document_checks='evidence/peer-readonly/go-zig-round3/document-checks.json',handoff='evidence/peer-readonly/go-zig-round3/handoff.json',concurrent_reference_changes=drift,report_artifacts=arts,parent_checkpoint=dict(parent_thread_id='f1059e32-7dfe-4169-b483-13c846782181',scope_client_request_id='round3-research-scope',progress_client_request_id='round3-research-progress1',delivery='steered'))
(e/'provenance.json').write_text(json.dumps(prov,indent=2)+'\n')
print(json.dumps(dict(report_artifacts=arts[:2],handoff=handoff,concurrent_reference_changes=drift),indent=2))
