#!/bin/sh
# Smoke tests for the compiler CLI, launcher, language features, both code
# generation paths, diagnostics, runtime errors, and exit statuses.
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
compiler=${MINYAR_TEST_COMPILER:-"$project_dir/build/minyarc"}
clang_command=${MINYAR_TEST_CLANG:-clang}
runtime="$project_dir/build/minyar-runtime.o"
if [ ! -f "$runtime" ]; then
    runtime="$project_dir/runtime/minyar_runtime.c"
fi
build_dir="$project_dir/build/smoke"
mkdir -p "$build_dir"
started=$(date +%s)
checks=0

pass() {
    checks=$((checks + 1))
}

fail() {
    echo "smoke test failed: $1" >&2
    shift
    for line in "$@"; do
        echo "  $line" >&2
    done
    exit 1
}

link() {
    "$clang_command" -O0 -Wno-override-module "$1" "$runtime" -o "$2"
}

# 1. The compiler's command line.
banner=$("$compiler" | sed -n '1p')
[ "$banner" = "Minyar compiler bootstrap is ready" ] || fail "compiler banner" "got: $banner"
pass

first_line=$("$compiler" "$project_dir/examples/hello.min" | sed -n '1p')
[ "$first_line" = "; Generated by the compiler written in Minyar." ] || fail "single-argument mode should write IR to stdout" "got: $first_line"
pass

rm -f "$build_dir/missing.ll"
if "$compiler" "$project_dir/does-not-exist.min" "$build_dir/missing.ll" 2>"$build_dir/missing.err"; then
    fail "a missing source file compiled"
fi
grep -q "could not be opened" "$build_dir/missing.err" || fail "missing source diagnostic" "$(cat "$build_dir/missing.err")"
[ ! -e "$build_dir/missing.ll" ] || fail "output file was written for a missing source"
pass

# 2. A compile-time error exits with status 1, reports in Minyar vocabulary,
#    and leaves no output behind.
rm -f "$build_dir/invalid.ll"
status=0
"$compiler" "$project_dir/tests/errors/type-mismatch.min" "$build_dir/invalid.ll" 2>"$build_dir/invalid.err" || status=$?
[ "$status" -eq 1 ] || fail "type error should exit with status 1" "status: $status"
first_error=$(sed -n '1p' "$build_dir/invalid.err")
case "$first_error" in
    "Minyar stopped: "*) ;;
    *) fail "diagnostics must begin with 'Minyar stopped:'" "got: $first_error" ;;
esac
grep -q "the value for 'answer' does not match its declared type" "$build_dir/invalid.err" || fail "type error text" "$(cat "$build_dir/invalid.err")"
[ ! -e "$build_dir/invalid.ll" ] || fail "output file was written for an invalid program"
pass

# 3. The language smoke program, through the single-module code path.
"$compiler" "$project_dir/tests/smoke/language.min" "$build_dir/language.ll"
link "$build_dir/language.ll" "$build_dir/language"
"$build_dir/language" > "$build_dir/language.out"
if ! cmp -s "$build_dir/language.out" "$project_dir/tests/smoke/expected-language.txt"; then
    diff "$project_dir/tests/smoke/expected-language.txt" "$build_dir/language.out" >&2 || true
    fail "language smoke program output changed"
fi
pass

# 4. The same program through the module-aware code path. A public declaration
#    in the entry file forces the multi-module pipeline; behaviour must match.
sed 's/^function factorial/public function factorial/' "$project_dir/tests/smoke/language.min" > "$build_dir/language-public.min"
"$compiler" "$build_dir/language-public.min" "$build_dir/language-public.ll"
link "$build_dir/language-public.ll" "$build_dir/language-public"
"$build_dir/language-public" > "$build_dir/language-public.out"
cmp -s "$build_dir/language-public.out" "$project_dir/tests/smoke/expected-language.txt" || fail "module-aware code path disagrees with single-module path"
pass

# 5. Compiling the same source twice is deterministic.
"$compiler" "$project_dir/tests/smoke/language.min" "$build_dir/language-again.ll"
cmp -s "$build_dir/language.ll" "$build_dir/language-again.ll" || fail "compiler output is not deterministic"
pass

# 6. Runtime stops exit with status 1 and explain themselves.
"$compiler" "$project_dir/tests/runtime/divide-by-zero.min" "$build_dir/divide.ll"
link "$build_dir/divide.ll" "$build_dir/divide"
status=0
"$build_dir/divide" > "$build_dir/divide.out" 2> "$build_dir/divide.err" || status=$?
[ "$status" -eq 1 ] || fail "runtime stop should exit with status 1" "status: $status"
grep -q "^Minyar stopped: an Integer cannot be divided by zero" "$build_dir/divide.err" || fail "runtime stop message" "$(cat "$build_dir/divide.err")"
pass

# 7. exit(status) propagates and output before it is flushed.
"$compiler" "$project_dir/tests/runtime/top-level-exit.min" "$build_dir/exit.ll"
link "$build_dir/exit.ll" "$build_dir/exit"
status=0
"$build_dir/exit" > "$build_dir/exit.out" || status=$?
[ "$status" -eq 7 ] || fail "exit(7) should set the process status" "status: $status"
[ "$(cat "$build_dir/exit.out")" = "before exit" ] || fail "output before exit" "$(cat "$build_dir/exit.out")"
pass

# 8. Command-line arguments reach the program.
"$compiler" "$project_dir/tests/runtime/text-and-files.min" "$build_dir/arguments.ll"
link "$build_dir/arguments.ll" "$build_dir/arguments"
output=$("$build_dir/arguments" first "$project_dir/examples/hello.min" "$build_dir/written.txt" | tr '\n' ' ')
[ "$output" = "6 M 42 3 first true " ] || fail "program arguments and file access" "got: $output"
[ "$(cat "$build_dir/written.txt")" = "Minyar" ] || fail "writeTextFile contents"
pass

# 9. The ./minyar wrapper: usage errors and a successful build with -o.
if [ -z "${MINYAR_TEST_COMPILER:-}" ]; then
    status=0
    "$project_dir/minyar" 2>/dev/null || status=$?
    [ "$status" -eq 2 ] || fail "wrapper without arguments should exit 2" "status: $status"
    status=0
    "$project_dir/minyar" "$project_dir/examples/hello.min" --bogus out 2>/dev/null || status=$?
    [ "$status" -eq 2 ] || fail "wrapper with a bad flag should exit 2" "status: $status"
    message=$("$project_dir/minyar" "$project_dir/examples/hello.min" -o "$build_dir/hello-wrapped")
    [ "$message" = "built $build_dir/hello-wrapped" ] || fail "wrapper build message" "got: $message"
    [ "$("$build_dir/hello-wrapped")" = "hello from LLVM-backed Minyar" ] || fail "wrapper-built program output"
    pass
fi

elapsed=$(( $(date +%s) - started ))
echo "smoke test passed: $checks checks in ${elapsed}s"
