from pathlib import Path
from collections import Counter
import ast,datetime,hashlib,json,math,re
ROOT=Path.cwd();OUT=ROOT/'evidence/peer-reconciliation';A=OUT/'round9-addendum';R='research/2026-10-memory/';TARGET=ROOT/R/'peer-evidence-reconciliation.json';d=json.loads(TARGET.read_text());manifest=json.loads((OUT/'round9-addendum-manifest.json').read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
def ref(rel,p=''):
 q=A/rel;return {'path':rel,'snapshot':str(q.relative_to(ROOT)),'sha256':sha(q.read_bytes()),'json_pointer':p}
checks=[];methods=[];executions=[];artifacts=[]
testrel='tests/memory-research-peer-projections.py';text=(A/testrel).read_text();tree=ast.parse(text)
for run,proposal,unitids in [('run-2a078047','P1',['G1','G2','G3','G10','L4','W1']),('run-ts2r1bcv','P2',['M1','M2','M3','M4','M5','M6','M7','M8'])]:
 base=R+'evidence/runtime-peer-projections/'+run+'/';x=json.loads((A/base/'results.json').read_text());prov=json.loads((A/base/'provenance.json').read_text());method=x['summary']['selected_test_name'];obs=[]
 node=next(n for n in ast.walk(tree) if isinstance(n,ast.FunctionDef) and n.name==method)
 ledger=ROOT/'evidence/peer-reconciliation/snapshot'/R/'peer-readonly-values-round9.json';report=ledger.with_suffix('.md');checks.append({'kind':'frozen_source_ledger_hash','run':run,'passed':sha(ledger.read_bytes())==prov['ledger_sha256'] and sha(report.read_bytes())==prov['review_sha256']})
 for ci,c in enumerate(x['coverage']):
  config=c['configuration'];cr=base+config+'-coverage.json';side=json.loads((A/cr).read_text());assert side['observed']==c['observed']
  runtime=next(check for check in x['checks'] if check['label']==config+'-runtime');flags=[f for f in runtime['command'] if re.fullmatch(r'-O(?:[0123szg]|fast)',f)];runtimeopt=flags[-1]
  checks.append({'kind':'runtime_compile_flags','run':run,'config':config,'passed':runtimeopt==('-O1' if 'sanitize' in config else '-O2') and runtime['returncode']==0})
  for oi,o in enumerate(c['observed']):
   obs.append({'run':run,'coverage':ref(cr,f'/observed/{oi}'),'source_sha256':sha(o['source'].encode()),'expected_sha256':sha(o['expected_stdout'].encode()),'expected_lines':len(o['expected_stdout'].splitlines()),'generated_definitions':o['generated_definitions'],'asan_definitions':o['asan_definitions']})
   if 'sanitize' in config:checks.append({'kind':'generated_asan_definitions','run':run,'passed':o['generated_definitions']==o['asan_definitions']==(13 if proposal=='P1' else 14)})
   for j,cmd in enumerate(o['commands']):
    if cmd['kind']!='execute':continue
    link=o['commands'][j-1];last=[f for f in link['argv'] if re.fullmatch(r'-O(?:[0123szg]|fast)',f)][-1];expected=sha(o['expected_stdout'].encode());ok=cmd['returncode']==0 and cmd['stdout_sha256']==expected
    checks.append({'kind':'saved_execution_and_last_optimizer','run':run,'config':config,'passed':ok and last==link['effective_last_optimization_flag'] and last in ['-O0','-O2']})
    executions.append({'id':f'{run}/{config}/{method}/{last}','run':run,'method':method,'config':config,'coverage':ref(cr,f'/observed/{oi}/commands/{j}'),'link':ref(cr,f'/observed/{oi}/commands/{j-1}'),'link_argv':link['argv'],'effective_last_optimization':last,'execution_argv':cmd['argv'],'returncode':cmd['returncode'],'stdout_sha256':cmd['stdout_sha256'],'expected_stdout_sha256':expected,'output_hash_matches':ok,'runtime_compile':runtime,'runtime_optimization':runtimeopt,'runtime_asan_ubsan':'sanitize' in config,'generated_asan_definition_check':{'definitions':o['generated_definitions'],'asan_definitions':o['asan_definitions']} if 'sanitize' in config else None,'generated_ubsan_claim':False,'lsan_enabled':False if 'sanitize' in config else None})
 for s in x['sources']:
  q=A/base/s['snapshot'];checks.append({'kind':'archived_round9_source_hash','run':run,'path':s['snapshot'],'passed':q.is_file() and sha(q.read_bytes())==s['sha256']})
 ids=[]
 for g in d['round2_through9_groups']:
  if g['record']['path']==R+'peer-readonly-values-round9.json' and g['authored_unit_id'] in unitids:
   ids.append(g['id']);g['later_addendum_original_minyar_methods']=[method];g['later_addendum_status']='selected_original_semantic_extension_executed; no full upstream port; original cutoff status retained'
 scoped=[e['id'] for e in executions if e['run']==run];assert len(scoped)==6
 methods.append({'method':method,'ledger':'peer-readonly-values-round9.json','proposal':proposal,'group_ids':unitids,'qualified_group_ids':ids,'run':run,'source':{'record':ref(testrel),'ast_span':[node.lineno,node.end_lineno],'body_sha256':sha(ast.get_source_segment(text,node).encode())},'archived_observations':obs,'execution_ids':scoped,'provenance':ref(base+'provenance.json'),'preregister':ref(base+'preregister.json'),'status':'saved_separate6_execution_baseline_pass; original coverage addition','compatible_existing_contract_and_assertion_extent':('Twelve signed64 Euclidean compositions: zero/sign/factor controls, consecutive maximum operands, half-factor, -2^31/1234 and consecutiveF92/F91; fixed magnitude expectations, abs inputs representable, positive divisor strictly decreases.' if proposal=='P1' else 'Eight equal/reversed Integer input pairs including both signed endpoints and equal endpoints; shared source slots become111/222, then both List roots dropped; returned scalar fields preserve explicit original minima/maxima.'),'excluded_semantics':('No std::gcd builtin, C++ common_type/templates/unsigned magnitudes/constexpr or abs(INT64_MIN) success.' if proposal=='P1' else 'No C++ scalar address/reference identity, input reference selection at ties, Float NaN tie policy or record value-copy semantics.'),'oracle_review':('Explicit12 expected answers; arithmetic factor/recurrence rationale and independent Python math.gcd/Fibonacci documentary checks, not same-Min yar-algorithm generated oracle.' if proposal=='P1' else 'Explicit eight endpoint/equality answer pairs plus independent shared mutation111/222;32 output lines. Equal-value outputs cannot establish which C++ input address is returned.'),'full_upstream_parity':False,'copied_upstream_code':'Conceptual inspiration; original Minyar program, no copy claimed; no exhaustive similarity audit.'})
 artifacts.append({'run':run,'results':ref(base+'results.json'),'status':x['status'],'compiler_sha256':x['compiler_sha256'],'sources':x['sources'],'summary_as_recorded':x['summary'],'derived_methods':1,'derived_execution_records':6,'effective_optimization_counts':dict(Counter(e['effective_last_optimization'] for e in executions if e['run']==run)),'scope':x['scope']})
 for p in d['proposal_status_overlay']:
  if p['id']=='peer-readonly-values-round9.json#'+proposal:p['later_addendum_current_view']={'status':'selected_original_extension_executed','method':method,'run':run,'full_upstream_parity':False,'cutoff_utc':manifest['cutoff_utc']}
pr=json.loads((A/R/'evidence/runtime-peer-projections/run-2a078047/preregister.json').read_text());e=pr['euclid'];checks.append({'kind':'independent_fixed_gcd_answers','passed':[math.gcd(a,b) for a,b in e['pairs']]==e['answers']});fib=[0,1]
for i in range(2,93):fib.append(fib[-1]+fib[-2])
checks.append({'kind':'consecutive_fibonacci_inputs','passed':e['pairs'][-1]==[fib[92],fib[91]]})
# Body identity checks preserve older selected source versions, not full-source rerun claims.
for m in d['original_minyar_methods']:
 node=next(n for n in ast.walk(tree) if isinstance(n,ast.FunctionDef) and n.name==m['method']);h=sha(ast.get_source_segment(text,node).encode());checks.append({'kind':'old_method_body_unchanged_in_later_source','method':m['method'],'passed':h==m['current_source']['ast_span']['sha256']})
assert not [c for c in checks if not c['passed']], [c for c in checks if not c['passed']]
add={'cutoff_utc':manifest['cutoff_utc'],'manifest':'evidence/peer-reconciliation/round9-addendum-manifest.json','changed_during_capture':manifest['changed_during_capture'],'basis':'Explicit user-provided saved archive paths, then independent documentary hash/argv/output checks. Original04:00:23 snapshot is unchanged.','methods':methods,'matrix_artifacts':artifacts,'archived_execution_records':executions,'checks':checks,'counts':{'new_methods':2,'new_executions':12,'source_group_inspiration_crosslinks':14,'checks_passed':len(checks),'checks_failed':0},'long_cohort_status':'User reports1,200-second native cohort healthy; still in progress, zero completion/pass claim.'}
d['round9_execution_addendum']=add;d['latest_current_view']={'cutoff_utc':manifest['cutoff_utc'],'distinct_projection_methods':13,'selected_execution_records':78,'scope_partition':[{'run':'run-l5_218bk','methods':8,'executions':48},*({'run':run,'methods':1,'executions':6} for run in ['run-1a2ft1yr','run-egbfb2e0','run-d29wceo4','run-2a078047','run-ts2r1bcv'])],'complete13_method_matrix':False,'source_report_group_count':646,'source_report_file_count':30,'proposal_exact_extension_crosslinks':13,'proposals_without_exact_extension_crosslink':20,'linked_group_inspiration_identities':133,'unlinked_group_identities':513,'counts_are_not_ports':True,'production_defect_or_change_from_projections':False}
for issue in d['findings_and_current_view_corrections']:
 if issue['id']=='C2':issue['later_addendum_resolution']={'evidence':ref(R+'README.md'),'status':'core updated evidence-index row to thirteen methods and separate cohorts; stale label present only in initial frozen cutoff'}
 if issue['id']=='C3':issue['later_addendum_resolution']='13 of33 proposals now link to selected executed extensions;20 lack exact crosslinks. Historical zero-execution source-lane records remain unchanged.'
 if issue['id']=='C8':issue['later_addendum_resolution']='Actual round9 archived results verified; each6executions. Original earlier in-progress status preserved as historical user observation.'
d['oracle_review_limits']['later_addendum']='Both round9 method bodies/explicit answers inspected; no implementation-mirroring expected generator or inappropriate peer semantic claim found. Arithmetic tests are bounded current-language value projections, not upstream APIs.'
TARGET.write_text(json.dumps(d,indent=2)+'\n');(OUT/'round9-addendum-checks.json').write_text(json.dumps({'passed':len(checks),'failed':0,'checks':checks},indent=2)+'\n');print(json.dumps(d['latest_current_view'],indent=2))
