ARG PEER
FROM ${PEER}
USER root
COPY setup-noop.sh /setup.sh
COPY peer-entrypoint.sh /minyar-peer-entrypoint.sh
RUN chmod 755 /setup.sh /minyar-peer-entrypoint.sh && mkdir -p /logs /downloads && chown 65534:65534 /logs /downloads
USER 65534:65534
ENTRYPOINT ["/minyar-peer-entrypoint.sh"]
