; Generated by the compiler written in Minyar.

@.text.data.110 = private unnamed_addr constant [2 x i8] c"Q\00"
@.text.110 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.110, i64 1, i64 1, ptr null, ptr null }
@.text.data.112 = private unnamed_addr constant [2 x i8] c"R\00"
@.text.112 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.112, i64 1, i64 1, ptr null, ptr null }
@.text.data.114 = private unnamed_addr constant [2 x i8] c"S\00"
@.text.114 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.114, i64 1, i64 1, ptr null, ptr null }

declare void @minyar_rc_enter(i64)
declare void @minyar_rc_leave()
declare void @minyar_stack_enter()
declare void @minyar_stack_leave()
declare void @minyar_rc_keep(ptr)
declare void @minyar_rc_borrow(ptr)
declare void @minyar_rc_retain(ptr)
declare void @minyar_rc_local(i64, ptr)
declare void @minyar_rc_local_take(i64, ptr)
declare void @minyar_rc_local_move(i64)
declare void @minyar_rc_step()
declare void @minyar_print_integer(i64)
declare void @minyar_print_text(ptr)
declare void @minyar_print_character(i32)
declare void @minyar_print_boolean(i1)
declare void @minyar_fail(ptr)
declare void @minyar_exit(i64)
declare void @minyar_print_float(double)
declare void @minyar_record_replace(ptr, i64, i64, i64)
declare i64 @minyar_bytes_get(ptr, i64)
declare void @minyar_bytes_set(ptr, i64, i64)
declare i64 @minyar_bytes_length(ptr)
declare i1 @minyar_file_exists(ptr)
declare ptr @minyar_bytes_new(i64)
declare void @minyar_bytes_resize(ptr, i64)
declare void @minyar_bytes_clear(ptr)
declare void @minyar_bytes_add(ptr, i64)
declare void @minyar_bytes_append(ptr, ptr)
declare ptr @minyar_bytes_slice(ptr, i64, i64)
declare ptr @minyar_read_bytes_file(ptr)
declare void @minyar_write_bytes_file(ptr, ptr)
declare void @minyar_bytes_add_int16(ptr, i64)
declare void @minyar_bytes_set_int16(ptr, i64, i64)
declare i64 @minyar_bytes_get_int16(ptr, i64)
declare void @minyar_bytes_add_uint16(ptr, i64)
declare void @minyar_bytes_set_uint16(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint16(ptr, i64)
declare void @minyar_bytes_add_int32(ptr, i64)
declare void @minyar_bytes_set_int32(ptr, i64, i64)
declare i64 @minyar_bytes_get_int32(ptr, i64)
declare void @minyar_bytes_add_uint32(ptr, i64)
declare void @minyar_bytes_set_uint32(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint32(ptr, i64)
declare void @minyar_bytes_add_int64(ptr, i64)
declare void @minyar_bytes_set_int64(ptr, i64, i64)
declare i64 @minyar_bytes_get_int64(ptr, i64)
declare void @minyar_bytes_add_float32(ptr, double)
declare void @minyar_bytes_set_float32(ptr, i64, double)
declare double @minyar_bytes_get_float32(ptr, i64)
declare void @minyar_bytes_add_float64(ptr, double)
declare void @minyar_bytes_set_float64(ptr, i64, double)
declare double @minyar_bytes_get_float64(ptr, i64)
declare ptr @minyar_float_text(double)
declare i64 @minyar_float_integer(double)
declare i32 @minyar_integer_character(i64)
declare i64 @minyar_integer_absolute(i64)
declare void @minyar_check_clamp_integer(i64, i64)
declare void @minyar_check_clamp_float(double, double)
declare void @minyar_check_shift(i64)
declare double @minyar_tan(double)
declare double @minyar_asin(double)
declare double @minyar_acos(double)
declare double @minyar_atan(double)
declare double @minyar_atan2(double, double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)
declare i1 @minyar_texts_are_equal(ptr, ptr)
declare ptr @minyar_join_text(ptr, ptr)
declare ptr @minyar_join_text_take_left(ptr, ptr)
declare ptr @minyar_join_texts(ptr)
declare i64 @minyar_text_length(ptr)
declare i64 @minyar_text_byte_length(ptr)
declare i32 @minyar_text_character_at(ptr, i64)
declare ptr @minyar_text_slice(ptr, i64, i64)
declare ptr @minyar_integer_text(i64)
declare ptr @minyar_character_text(i32)
declare ptr @minyar_boolean_text(i1)
declare void @minyar_initialize_arguments(i32, ptr)
declare i64 @minyar_argument_count()
declare ptr @minyar_argument(i64)
declare ptr @minyar_read_text_file(ptr)
declare void @minyar_write_text_file(ptr, ptr)
declare ptr @minyar_list_new()
declare void @minyar_list_references(ptr)
declare void @minyar_list_add(ptr, i64)
declare void @minyar_list_add_take(ptr, i64)
declare i64 @minyar_list_length(ptr)
declare i64 @minyar_list_get(ptr, i64)
declare void @minyar_list_set(ptr, i64, i64)
declare void @minyar_list_set_take(ptr, i64, i64)
declare ptr @minyar_list_appended(ptr, i64, i64, i64)
declare ptr @minyar_record_new(i64)
declare ptr @minyar_record_new_scalar(i64)
declare i64 @minyar_record_get(ptr, i64)
declare void @minyar_record_set(ptr, i64, i64)
declare void @minyar_record_set_scalar(ptr, i64, i64)
declare void @minyar_record_set_reference(ptr, i64, i64)
declare void @minyar_record_set_take(ptr, i64, i64)
declare void @minyar_check_integer_overflow(i1)
declare void @minyar_check_integer_division(i64, i64)
declare void @minyar_fail_integer_overflow() cold noreturn
declare void @minyar_fail_integer_division(i64) cold noreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)


; Checked inline List accesses. ABI: { values pointer, length, capacity }.
define internal i64 @.minyar.list.get.checked(ptr %list, i64 %position) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %get.valid = icmp ult i64 %position, %length
  br i1 %get.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  %value = load i64, ptr %slot
  ret i64 %value
bad:
  %fallback = call i64 @minyar_list_get(ptr %list, i64 %position)
  ret i64 %fallback
}
define internal void @.minyar.list.set.scalar.checked(ptr %list, i64 %position, i64 %value) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %set.valid = icmp ult i64 %position, %length
  br i1 %set.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  store i64 %value, ptr %slot
  ret void
bad:
  call void @minyar_list_set(ptr %list, i64 %position, i64 %value)
  ret void
}

define internal i64 @.minyar.list.length(ptr %list) alwaysinline sanitize_address {
entry:
  %pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %pointer
  ret i64 %length
}

define internal void @.minyar.integer.overflow.checked(i1 %overflow) alwaysinline sanitize_address {
entry:
  br i1 %overflow, label %bad, label %good
bad:
  call void @minyar_fail_integer_overflow()
  unreachable
good:
  ret void
}
define internal void @.minyar.integer.division.checked(i64 %left, i64 %right) alwaysinline sanitize_address {
entry:
  %zero = icmp eq i64 %right, 0
  %minimum = icmp eq i64 %left, -9223372036854775808
  %negative.one = icmp eq i64 %right, -1
  %overflow = and i1 %minimum, %negative.one
  %invalid = or i1 %zero, %overflow
  br i1 %invalid, label %bad, label %good
bad:
  call void @minyar_fail_integer_division(i64 %right)
  unreachable
good:
  ret void
}

define internal void @.minyar.shift.checked(i64 %count) alwaysinline sanitize_address {
entry:
  %valid = icmp ult i64 %count, 64
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_shift(i64 %count)
  ret void
good:
  ret void
}
define internal i32 @.minyar.character.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %range = icmp ult i64 %value, 1114112
  %below = icmp ult i64 %value, 55296
  %above = icmp ugt i64 %value, 57343
  %scalar = or i1 %below, %above
  %valid = and i1 %range, %scalar
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i32 @minyar_integer_character(i64 %value)
  ret i32 %fallback
good:
  %result = trunc i64 %value to i32
  ret i32 %result
}
define internal i64 @.minyar.float.integer.checked(double %value) alwaysinline sanitize_address {
entry:
  %above.minimum = fcmp oge double %value, -9.223372036854775808e18
  %below.maximum = fcmp olt double %value, 9.223372036854775808e18
  %valid = and i1 %above.minimum, %below.maximum
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_float_integer(double %value)
  ret i64 %fallback
good:
  %result = fptosi double %value to i64
  ret i64 %result
}
define internal i64 @.minyar.integer.absolute.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %valid = icmp ne i64 %value, -9223372036854775808
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_integer_absolute(i64 %value)
  ret i64 %fallback
good:
  %negative = icmp slt i64 %value, 0
  %negated = sub i64 0, %value
  %result = select i1 %negative, i64 %negated, i64 %value
  ret i64 %result
}
define internal void @.minyar.clamp.integer.checked(i64 %lower, i64 %upper) alwaysinline sanitize_address {
entry:
  %valid = icmp sle i64 %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_integer(i64 %lower, i64 %upper)
  ret void
good:
  ret void
}
define internal void @.minyar.clamp.float.checked(double %lower, double %upper) alwaysinline sanitize_address {
entry:
  %valid = fcmp ole double %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_float(double %lower, double %upper)
  ret void
good:
  ret void
}
define i32 @main(i32 %minyar.argument.count, ptr %minyar.argument.values) sanitize_address {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 5)
  %local.0 = alloca i64
  %local.1 = alloca i64
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %local.5 = alloca i64
  %local.6 = alloca i64
  %local.7 = alloca i64
  %local.8 = alloca i64
  %local.9 = alloca i64
  %local.10 = alloca i64
  %local.11 = alloca i64
  %local.12 = alloca i64
  %local.13 = alloca i64
  %local.14 = alloca i64
  %local.15 = alloca i64
  %local.16 = alloca i64
  %local.17 = alloca i64
  %local.18 = alloca i64
  call void @minyar_initialize_arguments(i32 %minyar.argument.count, ptr %minyar.argument.values)
  %value.0 = call ptr @minyar_list_new()
  call void @minyar_list_add(ptr %value.0, i64 4)
  call void @minyar_list_add(ptr %value.0, i64 7)
  call void @minyar_list_add(ptr %value.0, i64 9)
  call void @minyar_list_add(ptr %value.0, i64 13)
  call void @minyar_rc_local_take(i64 0, ptr %value.0)
  store ptr %value.0, ptr %local.0
  %value.1 = load ptr, ptr %local.0
  call void @minyar_rc_local(i64 1, ptr %value.1)
  store ptr %value.1, ptr %local.1
  store i64 0, ptr %local.2
  store i64 0, ptr %local.3
  store i64 0, ptr %local.4
  store i64 0, ptr %local.5
  store i64 0, ptr %local.6
  store i64 0, ptr %local.7
  store i64 0, ptr %local.8
  %value.2 = load ptr, ptr %local.0
  call void @minyar_rc_local(i64 2, ptr %value.2)
  store ptr %value.2, ptr %local.11
  store i64 0, ptr %local.9
  br label %for.condition.0

for.condition.0:
  %value.3 = load i64, ptr %local.9
  %value.4 = load ptr, ptr %local.11
  %value.5 = call i64 @minyar_list_length(ptr %value.4)
  %value.6 = icmp slt i64 %value.3, %value.5
  br i1 %value.6, label %for.body.1, label %for.end.3

for.body.1:
  %value.7 = load ptr, ptr %local.11
  %value.8 = call i64 @.minyar.list.get.checked(ptr %value.7, i64 %value.3)
  store i64 %value.8, ptr %local.12
  %value.9 = load i64, ptr %local.2
  store i64 %value.9, ptr %local.13
  %value.10 = load i64, ptr %local.2
  %checked.11 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.10, i64 1)
  %value.11 = extractvalue { i64, i1 } %checked.11, 0
  %overflow.11 = extractvalue { i64, i1 } %checked.11, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.11)
  store i64 %value.11, ptr %local.2
  %value.12 = load i64, ptr %local.3
  %checked.13 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.12, i64 1)
  %value.13 = extractvalue { i64, i1 } %checked.13, 0
  %overflow.13 = extractvalue { i64, i1 } %checked.13, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.13)
  store i64 %value.13, ptr %local.3
  %value.14 = load i64, ptr %local.7
  %checked.15 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.14, i64 10)
  %value.15 = extractvalue { i64, i1 } %checked.15, 0
  %overflow.15 = extractvalue { i64, i1 } %checked.15, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.15)
  %value.16 = load i64, ptr %local.13
  %checked.17 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.15, i64 %value.16)
  %value.17 = extractvalue { i64, i1 } %checked.17, 0
  %overflow.17 = extractvalue { i64, i1 } %checked.17, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.17)
  %checked.18 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.17, i64 1)
  %value.18 = extractvalue { i64, i1 } %checked.18, 0
  %overflow.18 = extractvalue { i64, i1 } %checked.18, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.18)
  store i64 %value.18, ptr %local.7
  %value.19 = load ptr, ptr %local.0
  %value.20 = load i64, ptr %local.13
  %value.21 = call i64 @.minyar.list.get.checked(ptr %value.19, i64 %value.20)
  %checked.22 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.21, i64 100)
  %value.22 = extractvalue { i64, i1 } %checked.22, 0
  %overflow.22 = extractvalue { i64, i1 } %checked.22, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.22)
  call void @.minyar.list.set.scalar.checked(ptr %value.19, i64 %value.20, i64 %value.22)
  %value.23 = load i64, ptr %local.5
  %checked.24 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.23, i64 100)
  %value.24 = extractvalue { i64, i1 } %checked.24, 0
  %overflow.24 = extractvalue { i64, i1 } %checked.24, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.24)
  %value.25 = load i64, ptr %local.12
  %checked.26 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.24, i64 %value.25)
  %value.26 = extractvalue { i64, i1 } %checked.26, 0
  %overflow.26 = extractvalue { i64, i1 } %checked.26, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.26)
  store i64 %value.26, ptr %local.5
  %value.27 = load i64, ptr %local.13
  %checked.28 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 900, i64 %value.27)
  %value.28 = extractvalue { i64, i1 } %checked.28, 0
  %overflow.28 = extractvalue { i64, i1 } %checked.28, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.28)
  store i64 %value.28, ptr %local.12
  %value.29 = load i64, ptr %local.6
  %value.30 = load i64, ptr %local.12
  %checked.31 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.29, i64 %value.30)
  %value.31 = extractvalue { i64, i1 } %checked.31, 0
  %overflow.31 = extractvalue { i64, i1 } %checked.31, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.31)
  store i64 %value.31, ptr %local.6
  %value.32 = call ptr @minyar_list_new()
  call void @minyar_list_references(ptr %value.32)
  %value.33 = ptrtoint ptr getelementptr (i8, ptr @.text.110, i64 8) to i64
  call void @minyar_list_add(ptr %value.32, i64 %value.33)
  %value.34 = ptrtoint ptr getelementptr (i8, ptr @.text.112, i64 8) to i64
  call void @minyar_list_add(ptr %value.32, i64 %value.34)
  %value.35 = ptrtoint ptr getelementptr (i8, ptr @.text.114, i64 8) to i64
  call void @minyar_list_add(ptr %value.32, i64 %value.35)
  call void @minyar_rc_local_take(i64 3, ptr %value.32)
  store ptr %value.32, ptr %local.14
  %value.36 = load i64, ptr %local.8
  %value.37 = load ptr, ptr %local.14
  %value.38 = call ptr @minyar_join_texts(ptr %value.37)
  call void @minyar_rc_keep(ptr %value.38)
  %value.39 = call i64 @minyar_text_length(ptr %value.38)
  %checked.40 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.36, i64 %value.39)
  %value.40 = extractvalue { i64, i1 } %checked.40, 0
  %overflow.40 = extractvalue { i64, i1 } %checked.40, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.40)
  store i64 %value.40, ptr %local.8
  call void @minyar_rc_step()
  %value.41 = load i64, ptr %local.13
  %value.42 = icmp eq i64 %value.41, 0
  br i1 %value.42, label %if.then.4, label %if.end.6

if.then.4:
  br label %for.step.2

if.end.6:
  %value.43 = load i64, ptr %local.13
  %value.44 = icmp eq i64 %value.43, 2
  br i1 %value.44, label %if.then.7, label %if.end.9

if.then.7:
  br label %for.end.3

if.end.9:
  %value.45 = load i64, ptr %local.4
  %checked.46 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.45, i64 1)
  %value.46 = extractvalue { i64, i1 } %checked.46, 0
  %overflow.46 = extractvalue { i64, i1 } %checked.46, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.46)
  store i64 %value.46, ptr %local.4
  call void @minyar_rc_local(i64 3, ptr null)
  br label %for.step.2

for.step.2:
  %value.47 = load i64, ptr %local.9
  %value.48 = add nsw i64 %value.47, 1
  store i64 %value.48, ptr %local.9
  call void @minyar_rc_step()
  br label %for.condition.0

for.end.3:
  call void @minyar_rc_local(i64 2, ptr null)
  call void @minyar_rc_step()
  %value.49 = load i64, ptr %local.5
  call void @minyar_print_integer(i64 %value.49)
  %value.50 = load i64, ptr %local.3
  call void @minyar_print_integer(i64 %value.50)
  %value.51 = load i64, ptr %local.2
  call void @minyar_print_integer(i64 %value.51)
  %value.52 = load i64, ptr %local.4
  call void @minyar_print_integer(i64 %value.52)
  %value.53 = load i64, ptr %local.6
  call void @minyar_print_integer(i64 %value.53)
  %value.54 = load i64, ptr %local.7
  call void @minyar_print_integer(i64 %value.54)
  %value.55 = load i64, ptr %local.8
  call void @minyar_print_integer(i64 %value.55)
  %value.56 = call ptr @minyar_list_new()
  call void @minyar_rc_local_take(i64 0, ptr %value.56)
  store ptr %value.56, ptr %local.0
  %value.57 = load ptr, ptr %local.1
  call void @minyar_rc_local(i64 4, ptr %value.57)
  store ptr %value.57, ptr %local.17
  store i64 0, ptr %local.15
  br label %for.condition.10

for.condition.10:
  %value.58 = load i64, ptr %local.15
  %value.59 = load ptr, ptr %local.17
  %value.60 = call i64 @minyar_list_length(ptr %value.59)
  %value.61 = icmp slt i64 %value.58, %value.60
  br i1 %value.61, label %for.body.11, label %for.end.13

for.body.11:
  %value.62 = load ptr, ptr %local.17
  %value.63 = call i64 @.minyar.list.get.checked(ptr %value.62, i64 %value.58)
  store i64 %value.63, ptr %local.18
  %value.64 = load i64, ptr %local.18
  call void @minyar_print_integer(i64 %value.64)
  br label %for.step.12

for.step.12:
  %value.65 = load i64, ptr %local.15
  %value.66 = add nsw i64 %value.65, 1
  store i64 %value.66, ptr %local.15
  call void @minyar_rc_step()
  br label %for.condition.10

for.end.13:
  call void @minyar_rc_local(i64 4, ptr null)
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i32 0
}

