#!/usr/bin/env python3
"""Package an already linked executable as a locally signed macOS application."""
import argparse
import os
from pathlib import Path
import plistlib
import re
import shutil
import subprocess
import tempfile


def package(binary, output, identifier):
    output = Path(os.path.abspath(output))
    if output.suffix != '.app' or not output.stem:
        raise ValueError('application output must have a name ending in .app')
    if not re.fullmatch(r'[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+', identifier):
        raise ValueError('bundle ID must be a dotted identifier using letters, digits, and hyphens')
    binary = Path(binary).resolve(strict=True)
    load_commands = subprocess.run(['otool', '-l', str(binary)], check=True,
                                   text=True, capture_output=True).stdout
    versions = re.findall(r'^\s*minos (\d+(?:\.\d+)*)\s*$', load_commands, re.MULTILINE)
    if not versions:
        versions = re.findall(r'cmd LC_VERSION_MIN_MACOSX\s+cmdsize \d+\s+version (\d+(?:\.\d+)*)', load_commands)
    if not versions:
        raise ValueError('could not read the macOS deployment target from the executable')
    minimum = max(versions, key=lambda v: tuple(int(n) for n in v.split('.')))
    output.parent.mkdir(parents=True, exist_ok=True)
    lock = output.with_name(output.name + '.minyar-lock')
    try:
        fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        raise ValueError(f'app output is locked by another build: {lock}') from None
    os.close(fd)
    try:
        if output.is_symlink() or (output.exists() and
                (not output.is_dir() or not (output / 'Contents/Resources/.minyar-app').is_file())):
            raise ValueError(f'refusing to replace an app not generated by Minyar: {output}')
        temp = Path(tempfile.mkdtemp(prefix='.minyar-app-', dir=output.parent))
        preserve_backup = False
        try:
            stage = temp / output.name
            contents = stage / 'Contents'
            (contents / 'MacOS').mkdir(parents=True)
            (contents / 'Resources').mkdir()
            executable = contents / 'MacOS' / 'application'
            shutil.copyfile(binary, executable)
            executable.chmod(0o755)
            info = {
                'CFBundleDevelopmentRegion': 'en',
                'CFBundleExecutable': 'application',
                'CFBundleIdentifier': identifier,
                'CFBundleInfoDictionaryVersion': '6.0',
                'CFBundleName': output.stem,
                'CFBundleDisplayName': output.stem,
                'CFBundlePackageType': 'APPL',
                'CFBundleShortVersionString': '1.0',
                'CFBundleVersion': '1',
                'LSMinimumSystemVersion': minimum,
                'NSHighResolutionCapable': True,
                'NSPrincipalClass': 'NSApplication',
            }
            (contents / 'Info.plist').write_bytes(plistlib.dumps(info))
            (contents / 'Resources/.minyar-app').write_text('Minyar generated application bundle v1\n')
            subprocess.run(['codesign', '--force', '--sign', '-', str(stage)], check=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            subprocess.run(['codesign', '--verify', '--strict', str(stage)], check=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            backup = temp / 'previous.app'
            if output.exists():
                os.replace(output, backup)
            try:
                os.replace(stage, output)
            except BaseException:
                if backup.exists():
                    try:
                        os.replace(backup, output)
                    except BaseException as error:
                        preserve_backup = True
                        raise OSError(f'installation and rollback failed; previous app preserved at {backup}') from error
                raise
        finally:
            if not preserve_backup:
                shutil.rmtree(temp)
    finally:
        lock.unlink()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binary', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--identifier', required=True)
    args = parser.parse_args()
    try:
        package(args.binary, args.output, args.identifier)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        detail = getattr(error, 'stderr', '') or ''
        if isinstance(detail, bytes):
            detail = detail.decode(errors='replace')
        parser.exit(1, f'macOS app packaging failed: {error}\n{detail}')


if __name__ == '__main__':
    main()
