; Generated by the compiler written in Minyar.

@.text.data.3 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.3 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.3, i64 2, i64 -1, ptr null, ptr null }
@.text.data.5 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.5 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.5, i64 4, i64 -1, ptr null, ptr null }
@.text.data.18 = private unnamed_addr constant [3 x i8] c"xy\00"
@.text.18 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.18, i64 2, i64 2, ptr null, ptr null }
@.text.data.74 = private unnamed_addr constant [2 x i8] c"x\00"
@.text.74 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.74, i64 1, i64 1, ptr null, ptr null }
@.text.data.76 = private unnamed_addr constant [2 x i8] c"y\00"
@.text.76 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.76, i64 1, i64 1, ptr null, ptr null }
@.text.data.81 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.81 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.81, i64 2, i64 -1, ptr null, ptr null }
@.text.data.83 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.83 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.83, i64 4, i64 -1, ptr null, ptr null }
@.text.data.143 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.143 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.143, i64 2, i64 -1, ptr null, ptr null }
@.text.data.145 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.145 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.145, i64 4, i64 -1, ptr null, ptr null }
@.text.data.150 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.150 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.150, i64 2, i64 -1, ptr null, ptr null }
@.text.data.152 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.152 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.152, i64 4, i64 -1, ptr null, ptr null }
@.text.data.212 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.212 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.212, i64 2, i64 -1, ptr null, ptr null }
@.text.data.214 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.214 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.214, i64 4, i64 -1, ptr null, ptr null }
@.text.data.283 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.283 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.283, i64 2, i64 -1, ptr null, ptr null }
@.text.data.285 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.285 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.285, i64 4, i64 -1, ptr null, ptr null }
@.text.data.298 = private unnamed_addr constant [1 x i8] c"\00"
@.text.298 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.298, i64 0, i64 0, ptr null, ptr null }
@.text.data.338 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.338 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.338, i64 2, i64 -1, ptr null, ptr null }
@.text.data.340 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.340 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.340, i64 4, i64 -1, ptr null, ptr null }
@.text.data.353 = private unnamed_addr constant [3 x i8] c"xy\00"
@.text.353 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.353, i64 2, i64 2, ptr null, ptr null }
@.text.data.378 = private unnamed_addr constant [3 x i8] c"é\00"
@.text.378 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.378, i64 2, i64 -1, ptr null, ptr null }
@.text.data.380 = private unnamed_addr constant [5 x i8] c"🙂\00"
@.text.380 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.380, i64 4, i64 -1, ptr null, ptr null }
@.text.data.398 = private unnamed_addr constant [3 x i8] c"xy\00"
@.text.398 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.398, i64 2, i64 2, ptr null, ptr null }
@.text.data.441 = private unnamed_addr constant [6 x i8] c"padé\00"
@.text.441 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.441, i64 5, i64 -1, ptr null, ptr null }
@.text.data.443 = private unnamed_addr constant [9 x i8] c"🙂tail\00"
@.text.443 = private global { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.443, i64 8, i64 -1, ptr null, ptr null }
@.text.data.468 = private unnamed_addr constant [3 x i8] c"xy\00"
@.text.468 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.468, i64 2, i64 2, ptr null, ptr null }

declare void @minyar_rc_enter(i64)
declare void @minyar_rc_leave()
declare void @minyar_stack_enter()
declare void @minyar_stack_leave()
declare void @minyar_rc_keep(ptr)
declare void @minyar_rc_borrow(ptr)
declare void @minyar_rc_retain(ptr)
declare void @minyar_rc_local(i64, ptr)
declare void @minyar_rc_local_take(i64, ptr)
declare void @minyar_rc_local_move(i64)
declare void @minyar_rc_step()
declare void @minyar_print_integer(i64)
declare void @minyar_print_text(ptr)
declare void @minyar_print_character(i32)
declare void @minyar_print_boolean(i1)
declare void @minyar_fail(ptr)
declare void @minyar_exit(i64)
declare void @minyar_print_float(double)
declare void @minyar_record_replace(ptr, i64, i64, i64)
declare i64 @minyar_bytes_get(ptr, i64)
declare void @minyar_bytes_set(ptr, i64, i64)
declare i64 @minyar_bytes_length(ptr)
declare i1 @minyar_file_exists(ptr)
declare ptr @minyar_bytes_new(i64)
declare void @minyar_bytes_resize(ptr, i64)
declare void @minyar_bytes_clear(ptr)
declare void @minyar_bytes_add(ptr, i64)
declare void @minyar_bytes_append(ptr, ptr)
declare ptr @minyar_bytes_slice(ptr, i64, i64)
declare ptr @minyar_read_bytes_file(ptr)
declare void @minyar_write_bytes_file(ptr, ptr)
declare void @minyar_bytes_add_int16(ptr, i64)
declare void @minyar_bytes_set_int16(ptr, i64, i64)
declare i64 @minyar_bytes_get_int16(ptr, i64)
declare void @minyar_bytes_add_uint16(ptr, i64)
declare void @minyar_bytes_set_uint16(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint16(ptr, i64)
declare void @minyar_bytes_add_int32(ptr, i64)
declare void @minyar_bytes_set_int32(ptr, i64, i64)
declare i64 @minyar_bytes_get_int32(ptr, i64)
declare void @minyar_bytes_add_uint32(ptr, i64)
declare void @minyar_bytes_set_uint32(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint32(ptr, i64)
declare void @minyar_bytes_add_int64(ptr, i64)
declare void @minyar_bytes_set_int64(ptr, i64, i64)
declare i64 @minyar_bytes_get_int64(ptr, i64)
declare void @minyar_bytes_add_float32(ptr, double)
declare void @minyar_bytes_set_float32(ptr, i64, double)
declare double @minyar_bytes_get_float32(ptr, i64)
declare void @minyar_bytes_add_float64(ptr, double)
declare void @minyar_bytes_set_float64(ptr, i64, double)
declare double @minyar_bytes_get_float64(ptr, i64)
declare ptr @minyar_float_text(double)
declare i64 @minyar_float_integer(double)
declare i32 @minyar_integer_character(i64)
declare i64 @minyar_integer_absolute(i64)
declare void @minyar_check_clamp_integer(i64, i64)
declare void @minyar_check_clamp_float(double, double)
declare void @minyar_check_shift(i64)
declare double @minyar_tan(double)
declare double @minyar_asin(double)
declare double @minyar_acos(double)
declare double @minyar_atan(double)
declare double @minyar_atan2(double, double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)
declare i1 @minyar_texts_are_equal(ptr, ptr)
declare ptr @minyar_join_text(ptr, ptr)
declare ptr @minyar_join_text_take_left(ptr, ptr)
declare ptr @minyar_join_texts(ptr)
declare i64 @minyar_text_length(ptr)
declare i64 @minyar_text_byte_length(ptr)
declare i32 @minyar_text_character_at(ptr, i64)
declare ptr @minyar_text_slice(ptr, i64, i64)
declare ptr @minyar_integer_text(i64)
declare ptr @minyar_character_text(i32)
declare ptr @minyar_boolean_text(i1)
declare void @minyar_initialize_arguments(i32, ptr)
declare i64 @minyar_argument_count()
declare ptr @minyar_argument(i64)
declare ptr @minyar_read_text_file(ptr)
declare void @minyar_write_text_file(ptr, ptr)
declare ptr @minyar_list_new()
declare void @minyar_list_references(ptr)
declare void @minyar_list_add(ptr, i64)
declare void @minyar_list_add_take(ptr, i64)
declare i64 @minyar_list_length(ptr)
declare i64 @minyar_list_get(ptr, i64)
declare void @minyar_list_set(ptr, i64, i64)
declare void @minyar_list_set_take(ptr, i64, i64)
declare ptr @minyar_list_appended(ptr, i64, i64, i64)
declare ptr @minyar_record_new(i64)
declare ptr @minyar_record_new_scalar(i64)
declare i64 @minyar_record_get(ptr, i64)
declare void @minyar_record_set(ptr, i64, i64)
declare void @minyar_record_set_scalar(ptr, i64, i64)
declare void @minyar_record_set_reference(ptr, i64, i64)
declare void @minyar_record_set_take(ptr, i64, i64)
declare void @minyar_check_integer_overflow(i1)
declare void @minyar_check_integer_division(i64, i64)
declare void @minyar_fail_integer_overflow() cold noreturn
declare void @minyar_fail_integer_division(i64) cold noreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)


; Checked inline List accesses. ABI: { values pointer, length, capacity }.
define internal i64 @.minyar.list.get.checked(ptr %list, i64 %position) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %get.valid = icmp ult i64 %position, %length
  br i1 %get.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  %value = load i64, ptr %slot
  ret i64 %value
bad:
  %fallback = call i64 @minyar_list_get(ptr %list, i64 %position)
  ret i64 %fallback
}
define internal void @.minyar.list.set.scalar.checked(ptr %list, i64 %position, i64 %value) alwaysinline sanitize_address {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %set.valid = icmp ult i64 %position, %length
  br i1 %set.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  store i64 %value, ptr %slot
  ret void
bad:
  call void @minyar_list_set(ptr %list, i64 %position, i64 %value)
  ret void
}

define internal i64 @.minyar.list.length(ptr %list) alwaysinline sanitize_address {
entry:
  %pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %pointer
  ret i64 %length
}

define internal void @.minyar.integer.overflow.checked(i1 %overflow) alwaysinline sanitize_address {
entry:
  br i1 %overflow, label %bad, label %good
bad:
  call void @minyar_fail_integer_overflow()
  unreachable
good:
  ret void
}
define internal void @.minyar.integer.division.checked(i64 %left, i64 %right) alwaysinline sanitize_address {
entry:
  %zero = icmp eq i64 %right, 0
  %minimum = icmp eq i64 %left, -9223372036854775808
  %negative.one = icmp eq i64 %right, -1
  %overflow = and i1 %minimum, %negative.one
  %invalid = or i1 %zero, %overflow
  br i1 %invalid, label %bad, label %good
bad:
  call void @minyar_fail_integer_division(i64 %right)
  unreachable
good:
  ret void
}

define internal void @.minyar.shift.checked(i64 %count) alwaysinline sanitize_address {
entry:
  %valid = icmp ult i64 %count, 64
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_shift(i64 %count)
  ret void
good:
  ret void
}
define internal i32 @.minyar.character.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %range = icmp ult i64 %value, 1114112
  %below = icmp ult i64 %value, 55296
  %above = icmp ugt i64 %value, 57343
  %scalar = or i1 %below, %above
  %valid = and i1 %range, %scalar
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i32 @minyar_integer_character(i64 %value)
  ret i32 %fallback
good:
  %result = trunc i64 %value to i32
  ret i32 %result
}
define internal i64 @.minyar.float.integer.checked(double %value) alwaysinline sanitize_address {
entry:
  %above.minimum = fcmp oge double %value, -9.223372036854775808e18
  %below.maximum = fcmp olt double %value, 9.223372036854775808e18
  %valid = and i1 %above.minimum, %below.maximum
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_float_integer(double %value)
  ret i64 %fallback
good:
  %result = fptosi double %value to i64
  ret i64 %result
}
define internal i64 @.minyar.integer.absolute.checked(i64 %value) alwaysinline sanitize_address {
entry:
  %valid = icmp ne i64 %value, -9223372036854775808
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_integer_absolute(i64 %value)
  ret i64 %fallback
good:
  %negative = icmp slt i64 %value, 0
  %negated = sub i64 0, %value
  %result = select i1 %negative, i64 %negated, i64 %value
  ret i64 %result
}
define internal void @.minyar.clamp.integer.checked(i64 %lower, i64 %upper) alwaysinline sanitize_address {
entry:
  %valid = icmp sle i64 %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_integer(i64 %lower, i64 %upper)
  ret void
good:
  ret void
}
define internal void @.minyar.clamp.float.checked(double %lower, double %upper) alwaysinline sanitize_address {
entry:
  %valid = fcmp ole double %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_float(double %lower, double %upper)
  ret void
good:
  ret void
}
define i32 @main(i32 %minyar.argument.count, ptr %minyar.argument.values) sanitize_address {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 12)
  %local.0 = alloca i64
  %local.1 = alloca i64
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %local.5 = alloca i64
  %local.6 = alloca i64
  %local.7 = alloca i64
  %local.8 = alloca i64
  %local.9 = alloca i64
  %local.10 = alloca i64
  %local.11 = alloca i64
  call void @minyar_initialize_arguments(i32 %minyar.argument.count, ptr %minyar.argument.values)
  %value.0 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.3, i64 8), ptr getelementptr (i8, ptr @.text.5, i64 8))
  call void @minyar_rc_local_take(i64 0, ptr %value.0)
  store ptr %value.0, ptr %local.0
  %value.1 = load ptr, ptr %local.0
  %value.2 = call i64 @minyar_text_length(ptr %value.1)
  call void @minyar_print_integer(i64 %value.2)
  %value.3 = load ptr, ptr %local.0
  call void @minyar_rc_local_move(i64 0)
  %value.4 = call ptr @minyar_join_text_take_left(ptr %value.3, ptr getelementptr (i8, ptr @.text.18, i64 8))
  call void @minyar_rc_local_take(i64 0, ptr %value.4)
  store ptr %value.4, ptr %local.0
  %value.5 = load ptr, ptr %local.0
  %value.6 = call i64 @minyar_text_length(ptr %value.5)
  call void @minyar_print_integer(i64 %value.6)
  %value.7 = load ptr, ptr %local.0
  %value.8 = call i32 @minyar_text_character_at(ptr %value.7, i64 0)
  call void @minyar_print_character(i32 %value.8)
  %value.9 = load ptr, ptr %local.0
  %value.10 = call i32 @minyar_text_character_at(ptr %value.9, i64 1)
  call void @minyar_print_character(i32 %value.10)
  %value.11 = load ptr, ptr %local.0
  %value.12 = call i32 @minyar_text_character_at(ptr %value.11, i64 2)
  call void @minyar_print_character(i32 %value.12)
  %value.13 = load ptr, ptr %local.0
  %value.14 = call i32 @minyar_text_character_at(ptr %value.13, i64 3)
  call void @minyar_print_character(i32 %value.14)
  %value.15 = load ptr, ptr %local.0
  %value.16 = call ptr @minyar_text_slice(ptr %value.15, i64 0, i64 2)
  call void @minyar_rc_keep(ptr %value.16)
  call void @minyar_print_text(ptr %value.16)
  call void @minyar_rc_step()
  %value.17 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.74, i64 8), ptr getelementptr (i8, ptr @.text.76, i64 8))
  call void @minyar_rc_local_take(i64 1, ptr %value.17)
  store ptr %value.17, ptr %local.1
  %value.18 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.81, i64 8), ptr getelementptr (i8, ptr @.text.83, i64 8))
  call void @minyar_rc_local_take(i64 2, ptr %value.18)
  store ptr %value.18, ptr %local.2
  %value.19 = load ptr, ptr %local.1
  %value.20 = call i64 @minyar_text_length(ptr %value.19)
  call void @minyar_print_integer(i64 %value.20)
  %value.21 = load ptr, ptr %local.2
  %value.22 = call i64 @minyar_text_length(ptr %value.21)
  call void @minyar_print_integer(i64 %value.22)
  %value.23 = load ptr, ptr %local.1
  %value.24 = load ptr, ptr %local.2
  call void @minyar_rc_local_move(i64 1)
  %value.25 = call ptr @minyar_join_text_take_left(ptr %value.23, ptr %value.24)
  call void @minyar_rc_local_take(i64 1, ptr %value.25)
  store ptr %value.25, ptr %local.1
  %value.26 = load ptr, ptr %local.1
  %value.27 = call i64 @minyar_text_length(ptr %value.26)
  call void @minyar_print_integer(i64 %value.27)
  %value.28 = load ptr, ptr %local.1
  %value.29 = call i32 @minyar_text_character_at(ptr %value.28, i64 2)
  call void @minyar_print_character(i32 %value.29)
  %value.30 = load ptr, ptr %local.1
  %value.31 = call i32 @minyar_text_character_at(ptr %value.30, i64 3)
  call void @minyar_print_character(i32 %value.31)
  %value.32 = load ptr, ptr %local.1
  %value.33 = call ptr @minyar_text_slice(ptr %value.32, i64 2, i64 4)
  call void @minyar_rc_keep(ptr %value.33)
  call void @minyar_print_text(ptr %value.33)
  call void @minyar_rc_step()
  %value.34 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.143, i64 8), ptr getelementptr (i8, ptr @.text.145, i64 8))
  call void @minyar_rc_local_take(i64 3, ptr %value.34)
  store ptr %value.34, ptr %local.3
  %value.35 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.150, i64 8), ptr getelementptr (i8, ptr @.text.152, i64 8))
  call void @minyar_rc_local_take(i64 4, ptr %value.35)
  store ptr %value.35, ptr %local.4
  %value.36 = load ptr, ptr %local.3
  %value.37 = call i64 @minyar_text_length(ptr %value.36)
  call void @minyar_print_integer(i64 %value.37)
  %value.38 = load ptr, ptr %local.4
  %value.39 = call i64 @minyar_text_length(ptr %value.38)
  call void @minyar_print_integer(i64 %value.39)
  %value.40 = load ptr, ptr %local.3
  %value.41 = load ptr, ptr %local.4
  call void @minyar_rc_local_move(i64 3)
  %value.42 = call ptr @minyar_join_text_take_left(ptr %value.40, ptr %value.41)
  call void @minyar_rc_local_take(i64 3, ptr %value.42)
  store ptr %value.42, ptr %local.3
  %value.43 = load ptr, ptr %local.3
  %value.44 = call i64 @minyar_text_length(ptr %value.43)
  call void @minyar_print_integer(i64 %value.44)
  %value.45 = load ptr, ptr %local.3
  %value.46 = call i32 @minyar_text_character_at(ptr %value.45, i64 2)
  call void @minyar_print_character(i32 %value.46)
  %value.47 = load ptr, ptr %local.3
  %value.48 = call i32 @minyar_text_character_at(ptr %value.47, i64 3)
  call void @minyar_print_character(i32 %value.48)
  %value.49 = load ptr, ptr %local.3
  %value.50 = call ptr @minyar_text_slice(ptr %value.49, i64 1, i64 3)
  call void @minyar_rc_keep(ptr %value.50)
  call void @minyar_print_text(ptr %value.50)
  call void @minyar_rc_step()
  %value.51 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.212, i64 8), ptr getelementptr (i8, ptr @.text.214, i64 8))
  call void @minyar_rc_local_take(i64 5, ptr %value.51)
  store ptr %value.51, ptr %local.5
  %value.52 = load ptr, ptr %local.5
  %value.53 = call i64 @minyar_text_length(ptr %value.52)
  call void @minyar_print_integer(i64 %value.53)
  %value.54 = load ptr, ptr %local.5
  %value.55 = load ptr, ptr %local.5
  call void @minyar_rc_local_move(i64 5)
  %value.56 = call ptr @minyar_join_text_take_left(ptr %value.54, ptr %value.55)
  call void @minyar_rc_local_take(i64 5, ptr %value.56)
  store ptr %value.56, ptr %local.5
  %value.57 = load ptr, ptr %local.5
  %value.58 = call i64 @minyar_text_length(ptr %value.57)
  call void @minyar_print_integer(i64 %value.58)
  %value.59 = load ptr, ptr %local.5
  %value.60 = call i32 @minyar_text_character_at(ptr %value.59, i64 0)
  call void @minyar_print_character(i32 %value.60)
  %value.61 = load ptr, ptr %local.5
  %value.62 = call i32 @minyar_text_character_at(ptr %value.61, i64 1)
  call void @minyar_print_character(i32 %value.62)
  %value.63 = load ptr, ptr %local.5
  %value.64 = call i32 @minyar_text_character_at(ptr %value.63, i64 2)
  call void @minyar_print_character(i32 %value.64)
  %value.65 = load ptr, ptr %local.5
  %value.66 = call i32 @minyar_text_character_at(ptr %value.65, i64 3)
  call void @minyar_print_character(i32 %value.66)
  %value.67 = load ptr, ptr %local.5
  %value.68 = call ptr @minyar_text_slice(ptr %value.67, i64 1, i64 3)
  call void @minyar_rc_keep(ptr %value.68)
  call void @minyar_print_text(ptr %value.68)
  call void @minyar_rc_step()
  %value.69 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.283, i64 8), ptr getelementptr (i8, ptr @.text.285, i64 8))
  call void @minyar_rc_local_take(i64 6, ptr %value.69)
  store ptr %value.69, ptr %local.6
  %value.70 = load ptr, ptr %local.6
  %value.71 = call i64 @minyar_text_length(ptr %value.70)
  call void @minyar_print_integer(i64 %value.71)
  %value.72 = load ptr, ptr %local.6
  call void @minyar_rc_local_move(i64 6)
  %value.73 = call ptr @minyar_join_text_take_left(ptr %value.72, ptr getelementptr (i8, ptr @.text.298, i64 8))
  call void @minyar_rc_local_take(i64 6, ptr %value.73)
  store ptr %value.73, ptr %local.6
  %value.74 = load ptr, ptr %local.6
  %value.75 = call i64 @minyar_text_length(ptr %value.74)
  call void @minyar_print_integer(i64 %value.75)
  %value.76 = load ptr, ptr %local.6
  %value.77 = call i32 @minyar_text_character_at(ptr %value.76, i64 0)
  call void @minyar_print_character(i32 %value.77)
  %value.78 = load ptr, ptr %local.6
  %value.79 = call i32 @minyar_text_character_at(ptr %value.78, i64 1)
  call void @minyar_print_character(i32 %value.79)
  %value.80 = load ptr, ptr %local.6
  %value.81 = call ptr @minyar_text_slice(ptr %value.80, i64 0, i64 1)
  call void @minyar_rc_keep(ptr %value.81)
  call void @minyar_print_text(ptr %value.81)
  call void @minyar_rc_step()
  %value.82 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.338, i64 8), ptr getelementptr (i8, ptr @.text.340, i64 8))
  call void @minyar_rc_local_take(i64 7, ptr %value.82)
  store ptr %value.82, ptr %local.7
  %value.83 = load ptr, ptr %local.7
  %value.84 = call i64 @minyar_text_length(ptr %value.83)
  call void @minyar_print_integer(i64 %value.84)
  %value.85 = load ptr, ptr %local.7
  call void @minyar_rc_local_move(i64 7)
  %value.86 = call ptr @minyar_join_text_take_left(ptr %value.85, ptr getelementptr (i8, ptr @.text.353, i64 8))
  call void @minyar_rc_local_take(i64 7, ptr %value.86)
  store ptr %value.86, ptr %local.7
  %value.87 = load ptr, ptr %local.7
  %value.88 = call ptr @minyar_text_slice(ptr %value.87, i64 0, i64 2)
  call void @minyar_rc_keep(ptr %value.88)
  call void @minyar_print_text(ptr %value.88)
  call void @minyar_rc_step()
  %value.89 = load ptr, ptr %local.7
  %value.90 = call i32 @minyar_text_character_at(ptr %value.89, i64 1)
  call void @minyar_print_character(i32 %value.90)
  %value.91 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.378, i64 8), ptr getelementptr (i8, ptr @.text.380, i64 8))
  call void @minyar_rc_local_take(i64 8, ptr %value.91)
  store ptr %value.91, ptr %local.8
  %value.92 = load ptr, ptr %local.8
  call void @minyar_rc_local(i64 9, ptr %value.92)
  store ptr %value.92, ptr %local.9
  %value.93 = load ptr, ptr %local.8
  %value.94 = call i64 @minyar_text_length(ptr %value.93)
  call void @minyar_print_integer(i64 %value.94)
  %value.95 = load ptr, ptr %local.8
  call void @minyar_rc_local_move(i64 8)
  %value.96 = call ptr @minyar_join_text_take_left(ptr %value.95, ptr getelementptr (i8, ptr @.text.398, i64 8))
  call void @minyar_rc_local_take(i64 8, ptr %value.96)
  store ptr %value.96, ptr %local.8
  %value.97 = load ptr, ptr %local.9
  %value.98 = call i64 @minyar_text_length(ptr %value.97)
  call void @minyar_print_integer(i64 %value.98)
  %value.99 = load ptr, ptr %local.9
  %value.100 = call i32 @minyar_text_character_at(ptr %value.99, i64 0)
  call void @minyar_print_character(i32 %value.100)
  %value.101 = load ptr, ptr %local.9
  %value.102 = call i32 @minyar_text_character_at(ptr %value.101, i64 1)
  call void @minyar_print_character(i32 %value.102)
  %value.103 = load ptr, ptr %local.8
  %value.104 = call i64 @minyar_text_length(ptr %value.103)
  call void @minyar_print_integer(i64 %value.104)
  %value.105 = load ptr, ptr %local.8
  %value.106 = call i32 @minyar_text_character_at(ptr %value.105, i64 1)
  call void @minyar_print_character(i32 %value.106)
  %value.107 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.441, i64 8), ptr getelementptr (i8, ptr @.text.443, i64 8))
  call void @minyar_rc_local_take(i64 10, ptr %value.107)
  store ptr %value.107, ptr %local.10
  %value.108 = load ptr, ptr %local.10
  %value.109 = call ptr @minyar_text_slice(ptr %value.108, i64 3, i64 5)
  call void @minyar_rc_local_take(i64 11, ptr %value.109)
  store ptr %value.109, ptr %local.11
  %value.110 = load ptr, ptr %local.11
  %value.111 = call i64 @minyar_text_length(ptr %value.110)
  call void @minyar_print_integer(i64 %value.111)
  %value.112 = load ptr, ptr %local.11
  call void @minyar_rc_local_move(i64 11)
  %value.113 = call ptr @minyar_join_text_take_left(ptr %value.112, ptr getelementptr (i8, ptr @.text.468, i64 8))
  call void @minyar_rc_local_take(i64 11, ptr %value.113)
  store ptr %value.113, ptr %local.11
  %value.114 = load ptr, ptr %local.11
  %value.115 = call i64 @minyar_text_length(ptr %value.114)
  call void @minyar_print_integer(i64 %value.115)
  %value.116 = load ptr, ptr %local.11
  %value.117 = call i32 @minyar_text_character_at(ptr %value.116, i64 0)
  call void @minyar_print_character(i32 %value.117)
  %value.118 = load ptr, ptr %local.11
  %value.119 = call i32 @minyar_text_character_at(ptr %value.118, i64 1)
  call void @minyar_print_character(i32 %value.119)
  %value.120 = load ptr, ptr %local.10
  %value.121 = call ptr @minyar_text_slice(ptr %value.120, i64 3, i64 5)
  call void @minyar_rc_keep(ptr %value.121)
  call void @minyar_print_text(ptr %value.121)
  call void @minyar_rc_step()
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i32 0
}

