; Generated by the compiler written in Minyar.

@.text.data.224 = private unnamed_addr constant [4 x i8] c"MIN\00"
@.text.224 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.224, i64 3, i64 3, ptr null, ptr null }
@.text.data.226 = private unnamed_addr constant [4 x i8] c"YAR\00"
@.text.226 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.226, i64 3, i64 3, ptr null, ptr null }
@.text.data.258 = private unnamed_addr constant [4 x i8] c"NEW\00"
@.text.258 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.258, i64 3, i64 3, ptr null, ptr null }
@.text.data.260 = private unnamed_addr constant [2 x i8] c"!\00"
@.text.260 = private constant { i64, ptr, i64, i64, ptr, ptr } { i64 0, ptr @.text.data.260, i64 1, i64 1, ptr null, ptr null }

declare void @minyar_rc_enter(i64)
declare void @minyar_rc_leave()
declare void @minyar_stack_enter()
declare void @minyar_stack_leave()
declare void @minyar_rc_keep(ptr)
declare void @minyar_rc_borrow(ptr)
declare void @minyar_rc_retain(ptr)
declare void @minyar_rc_local(i64, ptr)
declare void @minyar_rc_local_take(i64, ptr)
declare void @minyar_rc_local_move(i64)
declare void @minyar_rc_step()
declare void @minyar_print_integer(i64)
declare void @minyar_print_text(ptr)
declare void @minyar_print_character(i32)
declare void @minyar_print_boolean(i1)
declare void @minyar_fail(ptr)
declare void @minyar_exit(i64)
declare void @minyar_print_float(double)
declare void @minyar_record_replace(ptr, i64, i64, i64)
declare i64 @minyar_bytes_get(ptr, i64)
declare void @minyar_bytes_set(ptr, i64, i64)
declare i64 @minyar_bytes_length(ptr)
declare i1 @minyar_file_exists(ptr)
declare ptr @minyar_bytes_new(i64)
declare void @minyar_bytes_resize(ptr, i64)
declare void @minyar_bytes_clear(ptr)
declare void @minyar_bytes_add(ptr, i64)
declare void @minyar_bytes_append(ptr, ptr)
declare ptr @minyar_bytes_slice(ptr, i64, i64)
declare ptr @minyar_read_bytes_file(ptr)
declare void @minyar_write_bytes_file(ptr, ptr)
declare void @minyar_bytes_add_int16(ptr, i64)
declare void @minyar_bytes_set_int16(ptr, i64, i64)
declare i64 @minyar_bytes_get_int16(ptr, i64)
declare void @minyar_bytes_add_uint16(ptr, i64)
declare void @minyar_bytes_set_uint16(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint16(ptr, i64)
declare void @minyar_bytes_add_int32(ptr, i64)
declare void @minyar_bytes_set_int32(ptr, i64, i64)
declare i64 @minyar_bytes_get_int32(ptr, i64)
declare void @minyar_bytes_add_uint32(ptr, i64)
declare void @minyar_bytes_set_uint32(ptr, i64, i64)
declare i64 @minyar_bytes_get_uint32(ptr, i64)
declare void @minyar_bytes_add_int64(ptr, i64)
declare void @minyar_bytes_set_int64(ptr, i64, i64)
declare i64 @minyar_bytes_get_int64(ptr, i64)
declare void @minyar_bytes_add_float32(ptr, double)
declare void @minyar_bytes_set_float32(ptr, i64, double)
declare double @minyar_bytes_get_float32(ptr, i64)
declare void @minyar_bytes_add_float64(ptr, double)
declare void @minyar_bytes_set_float64(ptr, i64, double)
declare double @minyar_bytes_get_float64(ptr, i64)
declare ptr @minyar_float_text(double)
declare i64 @minyar_float_integer(double)
declare i32 @minyar_integer_character(i64)
declare i64 @minyar_integer_absolute(i64)
declare void @minyar_check_clamp_integer(i64, i64)
declare void @minyar_check_clamp_float(double, double)
declare void @minyar_check_shift(i64)
declare double @minyar_tan(double)
declare double @minyar_asin(double)
declare double @minyar_acos(double)
declare double @minyar_atan(double)
declare double @minyar_atan2(double, double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)
declare i1 @minyar_texts_are_equal(ptr, ptr)
declare ptr @minyar_join_text(ptr, ptr)
declare ptr @minyar_join_text_take_left(ptr, ptr)
declare ptr @minyar_join_texts(ptr)
declare i64 @minyar_text_length(ptr)
declare i64 @minyar_text_byte_length(ptr)
declare i32 @minyar_text_character_at(ptr, i64)
declare ptr @minyar_text_slice(ptr, i64, i64)
declare ptr @minyar_integer_text(i64)
declare ptr @minyar_character_text(i32)
declare ptr @minyar_boolean_text(i1)
declare void @minyar_initialize_arguments(i32, ptr)
declare i64 @minyar_argument_count()
declare ptr @minyar_argument(i64)
declare ptr @minyar_read_text_file(ptr)
declare void @minyar_write_text_file(ptr, ptr)
declare ptr @minyar_list_new()
declare void @minyar_list_references(ptr)
declare void @minyar_list_add(ptr, i64)
declare void @minyar_list_add_take(ptr, i64)
declare i64 @minyar_list_length(ptr)
declare i64 @minyar_list_get(ptr, i64)
declare void @minyar_list_set(ptr, i64, i64)
declare void @minyar_list_set_take(ptr, i64, i64)
declare ptr @minyar_list_appended(ptr, i64, i64, i64)
declare ptr @minyar_record_new(i64)
declare ptr @minyar_record_new_scalar(i64)
declare i64 @minyar_record_get(ptr, i64)
declare void @minyar_record_set(ptr, i64, i64)
declare void @minyar_record_set_scalar(ptr, i64, i64)
declare void @minyar_record_set_reference(ptr, i64, i64)
declare void @minyar_record_set_take(ptr, i64, i64)
declare void @minyar_check_integer_overflow(i1)
declare void @minyar_check_integer_division(i64, i64)
declare void @minyar_fail_integer_overflow() cold noreturn
declare void @minyar_fail_integer_division(i64) cold noreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)


; Checked inline List accesses. ABI: { values pointer, length, capacity }.
define internal i64 @.minyar.list.get.checked(ptr %list, i64 %position) alwaysinline {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %get.valid = icmp ult i64 %position, %length
  br i1 %get.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  %value = load i64, ptr %slot
  ret i64 %value
bad:
  %fallback = call i64 @minyar_list_get(ptr %list, i64 %position)
  ret i64 %fallback
}
define internal void @.minyar.list.set.scalar.checked(ptr %list, i64 %position, i64 %value) alwaysinline {
entry:
  %length.pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %length.pointer
  %set.valid = icmp ult i64 %position, %length
  br i1 %set.valid, label %good, label %bad
good:
  %values = load ptr, ptr %list
  %slot = getelementptr i64, ptr %values, i64 %position
  store i64 %value, ptr %slot
  ret void
bad:
  call void @minyar_list_set(ptr %list, i64 %position, i64 %value)
  ret void
}

define internal i64 @.minyar.list.length(ptr %list) alwaysinline {
entry:
  %pointer = getelementptr { ptr, i64, i64 }, ptr %list, i32 0, i32 1
  %length = load i64, ptr %pointer
  ret i64 %length
}

define internal void @.minyar.integer.overflow.checked(i1 %overflow) alwaysinline {
entry:
  br i1 %overflow, label %bad, label %good
bad:
  call void @minyar_fail_integer_overflow()
  unreachable
good:
  ret void
}
define internal void @.minyar.integer.division.checked(i64 %left, i64 %right) alwaysinline {
entry:
  %zero = icmp eq i64 %right, 0
  %minimum = icmp eq i64 %left, -9223372036854775808
  %negative.one = icmp eq i64 %right, -1
  %overflow = and i1 %minimum, %negative.one
  %invalid = or i1 %zero, %overflow
  br i1 %invalid, label %bad, label %good
bad:
  call void @minyar_fail_integer_division(i64 %right)
  unreachable
good:
  ret void
}

define internal void @.minyar.shift.checked(i64 %count) alwaysinline {
entry:
  %valid = icmp ult i64 %count, 64
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_shift(i64 %count)
  ret void
good:
  ret void
}
define internal i32 @.minyar.character.checked(i64 %value) alwaysinline {
entry:
  %range = icmp ult i64 %value, 1114112
  %below = icmp ult i64 %value, 55296
  %above = icmp ugt i64 %value, 57343
  %scalar = or i1 %below, %above
  %valid = and i1 %range, %scalar
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i32 @minyar_integer_character(i64 %value)
  ret i32 %fallback
good:
  %result = trunc i64 %value to i32
  ret i32 %result
}
define internal i64 @.minyar.float.integer.checked(double %value) alwaysinline {
entry:
  %above.minimum = fcmp oge double %value, -9.223372036854775808e18
  %below.maximum = fcmp olt double %value, 9.223372036854775808e18
  %valid = and i1 %above.minimum, %below.maximum
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_float_integer(double %value)
  ret i64 %fallback
good:
  %result = fptosi double %value to i64
  ret i64 %result
}
define internal i64 @.minyar.integer.absolute.checked(i64 %value) alwaysinline {
entry:
  %valid = icmp ne i64 %value, -9223372036854775808
  br i1 %valid, label %good, label %bad
bad:
  %fallback = call i64 @minyar_integer_absolute(i64 %value)
  ret i64 %fallback
good:
  %negative = icmp slt i64 %value, 0
  %negated = sub i64 0, %value
  %result = select i1 %negative, i64 %negated, i64 %value
  ret i64 %result
}
define internal void @.minyar.clamp.integer.checked(i64 %lower, i64 %upper) alwaysinline {
entry:
  %valid = icmp sle i64 %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_integer(i64 %lower, i64 %upper)
  ret void
good:
  ret void
}
define internal void @.minyar.clamp.float.checked(double %lower, double %upper) alwaysinline {
entry:
  %valid = fcmp ole double %lower, %upper
  br i1 %valid, label %good, label %bad
bad:
  call void @minyar_check_clamp_float(double %lower, double %upper)
  ret void
good:
  ret void
}
define ptr @.minyar.fn.appendSequence(ptr %argument.0, i64 %argument.1) {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 0)
  %value.0 = call ptr @minyar_list_appended(ptr %argument.0, i64 %argument.1, i64 0, i64 0)
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret ptr %value.0
}

define i32 @main(i32 %minyar.argument.count, ptr %minyar.argument.values) {
entry:
  call void @minyar_stack_enter()
  call void @minyar_rc_enter(i64 6)
  %local.0 = alloca i64
  %local.1 = alloca i64
  %local.2 = alloca i64
  %local.3 = alloca i64
  %local.4 = alloca i64
  %local.5 = alloca i64
  %local.6 = alloca i64
  %local.7 = alloca i64
  call void @minyar_initialize_arguments(i32 %minyar.argument.count, ptr %minyar.argument.values)
  %value.0 = call ptr @minyar_list_new()
  call void @minyar_rc_local_take(i64 0, ptr %value.0)
  store ptr %value.0, ptr %local.0
  store i64 0, ptr %local.1
  br label %while.condition.0

while.condition.0:
  %value.1 = load i64, ptr %local.1
  %value.2 = icmp slt i64 %value.1, 1024
  br i1 %value.2, label %while.body.1, label %while.end.2

while.body.1:
  %value.3 = load ptr, ptr %local.0
  %value.4 = load i64, ptr %local.1
  %checked.5 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %value.4, i64 37)
  %value.5 = extractvalue { i64, i1 } %checked.5, 0
  %overflow.5 = extractvalue { i64, i1 } %checked.5, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.5)
  call void @minyar_list_add(ptr %value.3, i64 %value.5)
  %value.6 = load i64, ptr %local.1
  %checked.7 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.6, i64 1)
  %value.7 = extractvalue { i64, i1 } %checked.7, 0
  %overflow.7 = extractvalue { i64, i1 } %checked.7, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.7)
  store i64 %value.7, ptr %local.1
  call void @minyar_rc_step()
  br label %while.condition.0

while.end.2:
  %value.8 = load ptr, ptr %local.0
  call void @minyar_rc_local(i64 1, ptr %value.8)
  store ptr %value.8, ptr %local.2
  %value.9 = load ptr, ptr %local.0
  call void @minyar_rc_local(i64 2, ptr %value.9)
  store ptr %value.9, ptr %local.3
  store i64 0, ptr %local.1
  br label %while.condition.3

while.condition.3:
  %value.10 = load i64, ptr %local.1
  %value.11 = icmp slt i64 %value.10, 128
  br i1 %value.11, label %while.body.4, label %while.end.5

while.body.4:
  %value.12 = load ptr, ptr %local.3
  %value.13 = load i64, ptr %local.1
  %value.14 = call ptr @.minyar.fn.appendSequence(ptr %value.12, i64 %value.13)
  call void @minyar_rc_local_take(i64 2, ptr %value.14)
  store ptr %value.14, ptr %local.3
  %value.15 = load i64, ptr %local.1
  %checked.16 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.15, i64 1)
  %value.16 = extractvalue { i64, i1 } %checked.16, 0
  %overflow.16 = extractvalue { i64, i1 } %checked.16, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.16)
  store i64 %value.16, ptr %local.1
  call void @minyar_rc_step()
  br label %while.condition.3

while.end.5:
  store i64 0, ptr %local.4
  store i64 0, ptr %local.1
  br label %while.condition.6

while.condition.6:
  %value.17 = load i64, ptr %local.1
  %value.18 = load ptr, ptr %local.3
  %value.19 = call i64 @.minyar.list.length(ptr %value.18)
  %value.20 = icmp slt i64 %value.17, %value.19
  br i1 %value.20, label %while.body.7, label %while.end.8

while.body.7:
  %value.21 = load i64, ptr %local.4
  %value.22 = load ptr, ptr %local.3
  %value.23 = load i64, ptr %local.1
  %value.24 = call i64 @.minyar.list.get.checked(ptr %value.22, i64 %value.23)
  %checked.25 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.21, i64 %value.24)
  %value.25 = extractvalue { i64, i1 } %checked.25, 0
  %overflow.25 = extractvalue { i64, i1 } %checked.25, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.25)
  store i64 %value.25, ptr %local.4
  %value.26 = load i64, ptr %local.1
  %checked.27 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.26, i64 1)
  %value.27 = extractvalue { i64, i1 } %checked.27, 0
  %overflow.27 = extractvalue { i64, i1 } %checked.27, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.27)
  store i64 %value.27, ptr %local.1
  call void @minyar_rc_step()
  br label %while.condition.6

while.end.8:
  %value.28 = load ptr, ptr %local.2
  %value.29 = call i64 @.minyar.list.length(ptr %value.28)
  call void @minyar_print_integer(i64 %value.29)
  %value.30 = load ptr, ptr %local.2
  %value.31 = call i64 @.minyar.list.get.checked(ptr %value.30, i64 1023)
  call void @minyar_print_integer(i64 %value.31)
  %value.32 = load ptr, ptr %local.3
  %value.33 = call i64 @.minyar.list.length(ptr %value.32)
  call void @minyar_print_integer(i64 %value.33)
  %value.34 = load ptr, ptr %local.3
  %value.35 = call i64 @.minyar.list.get.checked(ptr %value.34, i64 1024)
  call void @minyar_print_integer(i64 %value.35)
  %value.36 = load ptr, ptr %local.3
  %value.37 = call i64 @.minyar.list.get.checked(ptr %value.36, i64 1151)
  call void @minyar_print_integer(i64 %value.37)
  %value.38 = load i64, ptr %local.4
  call void @minyar_print_integer(i64 %value.38)
  %value.39 = call ptr @minyar_list_new()
  call void @minyar_list_references(ptr %value.39)
  call void @minyar_rc_local_take(i64 3, ptr %value.39)
  store ptr %value.39, ptr %local.5
  store i64 0, ptr %local.1
  br label %while.condition.9

while.condition.9:
  %value.40 = load i64, ptr %local.1
  %value.41 = icmp slt i64 %value.40, 257
  br i1 %value.41, label %while.body.10, label %while.end.11

while.body.10:
  %value.42 = load ptr, ptr %local.5
  %value.43 = call ptr @minyar_record_new(i64 2)
  %value.44 = load i64, ptr %local.1
  call void @minyar_record_set(ptr %value.43, i64 0, i64 %value.44)
  %value.45 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.224, i64 8), ptr getelementptr (i8, ptr @.text.226, i64 8))
  %value.46 = ptrtoint ptr %value.45 to i64
  call void @minyar_record_set_take(ptr %value.43, i64 1, i64 %value.46)
  %value.47 = ptrtoint ptr %value.43 to i64
  call void @minyar_list_add_take(ptr %value.42, i64 %value.47)
  %value.48 = load i64, ptr %local.1
  %checked.49 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %value.48, i64 1)
  %value.49 = extractvalue { i64, i1 } %checked.49, 0
  %overflow.49 = extractvalue { i64, i1 } %checked.49, 1
  call void @.minyar.integer.overflow.checked(i1 %overflow.49)
  store i64 %value.49, ptr %local.1
  call void @minyar_rc_step()
  br label %while.condition.9

while.end.11:
  %value.50 = load ptr, ptr %local.5
  call void @minyar_rc_local(i64 4, ptr %value.50)
  store ptr %value.50, ptr %local.6
  %value.51 = load ptr, ptr %local.5
  %value.52 = call ptr @minyar_record_new(i64 2)
  call void @minyar_record_set(ptr %value.52, i64 0, i64 999)
  %value.53 = call ptr @minyar_join_text(ptr getelementptr (i8, ptr @.text.258, i64 8), ptr getelementptr (i8, ptr @.text.260, i64 8))
  %value.54 = ptrtoint ptr %value.53 to i64
  call void @minyar_record_set_take(ptr %value.52, i64 1, i64 %value.54)
  %value.55 = ptrtoint ptr %value.52 to i64
  %value.56 = call ptr @minyar_list_appended(ptr %value.51, i64 %value.55, i64 1, i64 1)
  call void @minyar_rc_local_take(i64 5, ptr %value.56)
  store ptr %value.56, ptr %local.7
  %value.57 = call ptr @minyar_list_new()
  call void @minyar_list_references(ptr %value.57)
  call void @minyar_rc_local_take(i64 3, ptr %value.57)
  store ptr %value.57, ptr %local.5
  %value.58 = load ptr, ptr %local.6
  %value.59 = call i64 @.minyar.list.length(ptr %value.58)
  call void @minyar_print_integer(i64 %value.59)
  %value.60 = load ptr, ptr %local.6
  %value.61 = call i64 @.minyar.list.get.checked(ptr %value.60, i64 256)
  %value.62 = inttoptr i64 %value.61 to ptr
  %value.63 = call i64 @minyar_record_get(ptr %value.62, i64 0)
  call void @minyar_print_integer(i64 %value.63)
  %value.64 = load ptr, ptr %local.6
  %value.65 = call i64 @.minyar.list.get.checked(ptr %value.64, i64 256)
  %value.66 = inttoptr i64 %value.65 to ptr
  %value.67 = call i64 @minyar_record_get(ptr %value.66, i64 1)
  %value.68 = inttoptr i64 %value.67 to ptr
  call void @minyar_rc_borrow(ptr %value.68)
  call void @minyar_print_text(ptr %value.68)
  call void @minyar_rc_step()
  %value.69 = load ptr, ptr %local.7
  %value.70 = call i64 @.minyar.list.length(ptr %value.69)
  call void @minyar_print_integer(i64 %value.70)
  %value.71 = load ptr, ptr %local.7
  %value.72 = call i64 @.minyar.list.get.checked(ptr %value.71, i64 0)
  %value.73 = inttoptr i64 %value.72 to ptr
  %value.74 = call i64 @minyar_record_get(ptr %value.73, i64 1)
  %value.75 = inttoptr i64 %value.74 to ptr
  call void @minyar_rc_borrow(ptr %value.75)
  call void @minyar_print_text(ptr %value.75)
  call void @minyar_rc_step()
  %value.76 = load ptr, ptr %local.7
  %value.77 = call i64 @.minyar.list.get.checked(ptr %value.76, i64 257)
  %value.78 = inttoptr i64 %value.77 to ptr
  %value.79 = call i64 @minyar_record_get(ptr %value.78, i64 1)
  %value.80 = inttoptr i64 %value.79 to ptr
  call void @minyar_rc_borrow(ptr %value.80)
  call void @minyar_print_text(ptr %value.80)
  call void @minyar_rc_step()
  call void @minyar_rc_leave()
  call void @minyar_stack_leave()
  ret i32 0
}

